(deftheme desert
  "A white on dark theme, like the desert theme of vim.")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'desert
   `(default ((,class (:background "gray20" :foreground "white"))))
   `(Buffer-menu-buffer-face ((,class (:bold t :weight bold))))
   `(CUA-global-mark-face ((,class (:background "cyan" :foreground "black"))))
   `(CUA-rectangle-face ((,class (:background "maroon" :foreground "white"))))
   `(CUA-rectangle-noselect-face ((,class (:background "dimgray" :foreground "white"))))
   `(Info-title-1-face ((,class (:bold t :weight bold :height 1.728 :family "helv"))))
   `(Info-title-2-face ((,class (:bold t :weight bold :height 1.44 :family "helv"))))
   `(Info-title-3-face ((,class (:bold t :weight bold :height 1.2 :family "helv"))))
   `(Info-title-4-face ((,class (:bold t :weight bold :family "helv"))))
   `(OrangeRed ((,class (nil))))
   `(antlr-font-lock-keyword-face ((,class (:bold t :foreground "Gray85" :weight bold))))
   `(antlr-font-lock-literal-face ((,class (:bold t :foreground "Gray85" :weight bold))))
   `(antlr-font-lock-ruledef-face ((,class (:bold t :foreground "Gray85" :weight bold))))
   `(antlr-font-lock-ruleref-face ((,class (:foreground "Gray85"))))
   `(antlr-font-lock-tokendef-face ((,class (:bold t :foreground "Gray85" :weight bold))))
   `(antlr-font-lock-tokenref-face ((,class (:foreground "Gray85"))))
   `(bbdb-company ((,class (:foreground "pale green"))))
   `(bbdb-field-name ((,class (:foreground "green"))))
   `(bbdb-field-value ((,class (:foreground "dark sea green"))))
   `(bbdb-name ((,class (:bold t :foreground "pale green" :weight bold))))
   `(bg:erc-color-face0 ((,class (:background "White"))))
   `(bg:erc-color-face1 ((,class (:background "black"))))
   `(bg:erc-color-face10 ((,class (:background "lightblue1"))))
   `(bg:erc-color-face11 ((,class (:background "cyan"))))
   `(bg:erc-color-face12 ((,class (:background "blue"))))
   `(bg:erc-color-face13 ((,class (:background "deeppink"))))
   `(bg:erc-color-face14 ((,class (:background "gray50"))))
   `(bg:erc-color-face15 ((,class (:background "gray90"))))
   `(bg:erc-color-face2 ((,class (:background "blue4"))))
   `(bg:erc-color-face3 ((,class (:background "green4"))))
   `(bg:erc-color-face4 ((,class (:background "red"))))
   `(bg:erc-color-face5 ((,class (:background "brown"))))
   `(bg:erc-color-face6 ((,class (:background "purple"))))
   `(bg:erc-color-face7 ((,class (:background "orange"))))
   `(bg:erc-color-face8 ((,class (:background "yellow"))))
   `(bg:erc-color-face9 ((,class (:background "green"))))
   `(blank-space-face ((,class (:background "LightGray"))))
   `(blank-tab-face ((,class (:background "Wheat"))))
   `(blue ((,class (:bold t :foreground "blue" :weight bold))))
   `(bold ((,class (:bold t :foreground "#00CC00" :weight bold))))
   `(bold-italic ((,class (:italic t :bold t :slant oblique :weight semi-bold))))
   `(border ((,class (:background "black"))))
   `(border-glyph ((,class (:bold t :weight bold))))
   `(buffer-menu-buffer ((,class (:bold t :weight bold))))
   `(buffers-tab ((,class (:background "black" :foreground "LightSkyBlue"))))
   `(button ((,class (:bold t :underline t :weight bold))))
   `(c-nonbreakable-space-face ((,class (:bold t :background "#332200" :weight bold))))
   `(calendar-today-face ((,class (:underline t))))
   `(change-log-acknowledgement-face ((,class (:foreground "LightBlue"))))
   `(change-log-conditionals-face ((,class (:bold t :foreground "Aquamarine" :weight bold))))
   `(change-log-date-face ((,class (:foreground "LightSalmon"))))
   `(change-log-email-face ((,class (:bold t :foreground "Aquamarine" :weight bold))))
   `(change-log-file-face ((,class (:bold t :foreground "Aquamarine" :weight bold))))
   `(change-log-function-face ((,class (:bold t :foreground "Aquamarine" :weight bold))))
   `(change-log-list-face ((,class (:foreground "Salmon"))))
   `(change-log-name-face ((,class (:foreground "Aquamarine"))))
   `(clearcase-dired-checkedout-face ((,class (:foreground "red"))))
   `(cmode-bracket-face ((,class (:bold t :weight bold))))
   `(color-mode-face-@ ((,class (:foreground "orange"))))
   `(color-mode-face-a ((,class (:foreground "blue"))))
   `(color-mode-face-b ((,class (:foreground "red"))))
   `(color-mode-face-c ((,class (:foreground "green3"))))
   `(color-mode-face-d ((,class (:background "red" :foreground "white"))))
   `(color-mode-face-e ((,class (:background "orange" :foreground "blue"))))
   `(color-mode-face-f ((,class (:background "blue" :foreground "yellow"))))
   `(color-mode-face-g ((,class (:background "lightblue" :foreground "brown"))))
   `(color-mode-face-h ((,class (:background "brown" :foreground "white"))))
   `(comint-highlight-input ((,class (nil))))
   `(comint-highlight-prompt ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(comint-input-face ((,class (:foreground "deepskyblue"))))
   `(compilation-column-number ((,class (nil))))
   `(compilation-error ((,class (:bold t :weight semi-bold :foreground "#00CC00" :background "darkblue"))))
   `(compilation-info ((,class (:bold t :foreground "Green1" :weight bold))))
   `(compilation-line-number ((,class (nil))))
   `(compilation-warning ((,class (:bold t :foreground "Orange" :weight bold))))
   `(completions-annotations ((,class (:italic t :bold t :weight bold :slant oblique :foreground "#00CC00" :background "black"))))
   `(completions-common-part ((,class (:family "Consolas" :foundry "microsoft" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#00CC00" :background "black" :stipple nil :height 143))))
   `(completions-first-difference ((,class (:bold t :weight bold :foreground "#00CC00" :background "black"))))
   `(cparen-around-andor-face ((,class (:bold t :foreground "maroon" :weight bold))))
   `(cparen-around-begin-face ((,class (:foreground "maroon"))))
   `(cparen-around-conditional-face ((,class (:bold t :foreground "RoyalBlue" :weight bold))))
   `(cparen-around-define-face ((,class (:bold t :foreground "Blue" :weight bold))))
   `(cparen-around-lambda-face ((,class (:foreground "LightSeaGreen"))))
   `(cparen-around-letdo-face ((,class (:bold t :foreground "LightSeaGreen" :weight bold))))
   `(cparen-around-quote-face ((,class (:foreground "SaddleBrown"))))
   `(cparen-around-set!-face ((,class (:foreground "OrangeRed"))))
   `(cparen-around-syntax-rules-face ((,class (:foreground "Magenta"))))
   `(cparen-around-vector-face ((,class (:foreground "chocolate"))))
   `(cparen-binding-face ((,class (:foreground "ForestGreen"))))
   `(cparen-binding-list-face ((,class (:bold t :foreground "ForestGreen" :weight bold))))
   `(cparen-conditional-clause-face ((,class (:foreground "RoyalBlue"))))
   `(cparen-normal-paren-face ((,class (:foreground "grey50"))))
   `(cperl-array-face ((,class (:bold t :background "lightyellow2" :foreground "Blue" :weight bold))))
   `(cperl-hash-face ((,class (:italic t :bold t :background "lightyellow2" :foreground "Red" :slant italic :weight bold))))
   `(cperl-here-face ((,class (:background "gray68" :foreground "DeepPink"))))
   `(cperl-invalid-face ((,class (:foreground "white"))))
   `(cperl-nonoverridable-face ((,class (:foreground "chartreuse3"))))
   `(cperl-pod-face ((,class (nil))))
   `(cperl-pod-head-face ((,class (nil))))
   `(cursor ((,class (:background "green"))))
   `(custom-button-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(custom-button-pressed-face ((,class (nil))))
   `(custom-changed-face ((,class (:italic t :background "black" :foreground "#00CC00" :slant oblique))))
   `(custom-comment-face ((,class (nil))))
   `(custom-comment-tag-face ((,class (nil))))
   `(custom-documentation-face ((,class (nil))))
   `(custom-face-tag-face ((,class (nil))))
   `(custom-group-tag-face ((,class (nil))))
   `(custom-group-tag-face-1 ((,class (nil))))
   `(custom-invalid-face ((,class (:background "black" :foreground "#00CC00" :strike-through t))))
   `(custom-modified-face ((,class (nil))))
   `(custom-rogue-face ((,class (nil))))
   `(custom-saved-face ((,class (nil))))
   `(custom-set-face ((,class (nil))))
   `(custom-state-face ((,class (nil))))
   `(custom-variable-button-face ((,class (nil))))
   `(custom-variable-tag-face ((,class (nil))))
   `(cvs-filename-face ((,class (:foreground "white"))))
   `(cvs-handled-face ((,class (:foreground "pink"))))
   `(cvs-header-face ((,class (:bold t :foreground "green" :weight bold))))
   `(cvs-marked-face ((,class (:bold t :foreground "green3" :weight bold))))
   `(cvs-msg-face ((,class (:italic t :foreground "red" :slant italic))))
   `(cvs-need-action-face ((,class (:foreground "yellow"))))
   `(cvs-unknown-face ((,class (:foreground "grey"))))
   `(cyan ((,class (:foreground "cyan"))))
   `(date ((,class (:foreground "green"))))
   `(diary-face ((,class (:foreground "red"))))
   `(diff-added-face ((,class (nil))))
   `(diff-changed-face ((,class (nil))))
   `(diff-context-face ((,class (:foreground "grey70"))))
   `(diff-file-header-face ((,class (:bold t :weight bold))))
   `(diff-function-face ((,class (:foreground "grey70"))))
   `(diff-header-face ((,class (:foreground "light salmon"))))
   `(diff-hunk-header-face ((,class (:foreground "light salmon"))))
   `(diff-index-face ((,class (:bold t :weight bold))))
   `(diff-nonexistent-face ((,class (:bold t :weight bold))))
   `(diff-removed-face ((,class (nil))))
   `(dired-directory ((,class (:bold t :weight bold :foreground "#00CC00" :background "black"))))
   `(dired-face-boring ((,class (:foreground "Gray65"))))
   `(dired-face-directory ((,class (:bold t :foreground "sky blue" :weight bold))))
   `(dired-face-executable ((,class (:foreground "green yellow"))))
   `(dired-face-flagged ((,class (:foreground "tomato"))))
   `(dired-face-header ((,class (:background "grey75" :foreground "black"))))
   `(dired-face-marked ((,class (:foreground "light salmon"))))
   `(dired-face-permissions ((,class (:foreground "aquamarine"))))
   `(dired-face-setuid ((,class (:foreground "Red"))))
   `(dired-face-socket ((,class (:foreground "magenta"))))
   `(dired-face-symlink ((,class (:foreground "cyan"))))
   `(dired-flagged ((,class (:bold t :weight semi-bold :foreground "#00CC00" :background "darkblue"))))
   `(dired-header ((,class (nil))))
   `(dired-ignored ((,class (:foreground "grey50"))))
   `(dired-mark ((,class (nil))))
   `(dired-marked ((,class (:bold t :weight semi-bold :foreground "#00CC00" :background "darkblue"))))
   `(dired-perm-write ((,class (:background "black" :foreground "medium spring green"))))
   `(dired-symlink ((,class (:bold t :weight semi-bold :underline t :foreground "green" :background "black"))))
   `(dired-warning ((,class (:bold t :weight semi-bold :foreground "#00CC00" :background "darkblue"))))
   `(display-time-mail-balloon-enhance-face ((,class (:bold t :background "wheat" :foreground "black" :weight bold))))
   `(display-time-mail-balloon-gnus-group-face ((,class (:bold t :background "wheat" :foreground "blue" :weight bold))))
   `(display-time-time-balloon-face ((,class (:bold t :background "light salmon" :foreground "dark green" :weight bold))))
   `(ebrowse-default-face ((,class (nil))))
   `(ebrowse-file-name-face ((,class (:italic t :slant italic))))
   `(ebrowse-member-attribute-face ((,class (:foreground "red"))))
   `(ebrowse-member-class-face ((,class (:foreground "Gray85"))))
   `(ebrowse-progress-face ((,class (:background "blue"))))
   `(ebrowse-root-class-face ((,class (:bold t :foreground "Gray85" :weight bold))))
   `(ebrowse-tree-mark-face ((,class (:foreground "Gray85"))))
   `(ecb-bucket-token-face ((,class (:bold t :weight bold))))
   `(ecb-default-general-face ((,class (:height 1.0))))
   `(ecb-default-highlight-face ((,class (:background "magenta" :height 1.0))))
   `(ecb-directories-general-face ((,class (:height 0.9))))
   `(ecb-directory-face ((,class (:background "Cyan4"))))
   `(ecb-history-face ((,class (:background "Cyan4"))))
   `(ecb-history-general-face ((,class (:height 0.9))))
   `(ecb-method-face ((,class (:background "Cyan4" :slant normal :weight normal))))
   `(ecb-methods-general-face ((,class (:slant normal))))
   `(ecb-source-face ((,class (:background "Cyan4"))))
   `(ecb-source-in-directories-buffer-face ((,class (:foreground "LightBlue1"))))
   `(ecb-sources-face ((,class (:foreground "LightBlue1"))))
   `(ecb-sources-general-face ((,class (:height 0.9))))
   `(ecb-token-header-face ((,class (:background "Steelblue4"))))
   `(ecb-type-token-class-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-enum-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-group-face ((,class (:bold t :foreground "dim gray" :weight bold))))
   `(ecb-type-token-interface-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-struct-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-typedef-face ((,class (:bold t :weight bold))))
   `(ediff-current-diff-face-A ((,class (:background "pale green" :foreground "firebrick"))))
   `(ediff-current-diff-face-Ancestor ((,class (:background "VioletRed" :foreground "Black"))))
   `(ediff-current-diff-face-B ((,class (:background "Yellow" :foreground "DarkOrchid"))))
   `(ediff-current-diff-face-C ((,class (:background "Pink" :foreground "Navy"))))
   `(ediff-even-diff-face-A ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-even-diff-face-Ancestor ((,class (:background "Grey" :foreground "White"))))
   `(ediff-even-diff-face-B ((,class (:background "Grey" :foreground "White"))))
   `(ediff-even-diff-face-C ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-fine-diff-face-A ((,class (:background "sky blue" :foreground "Navy"))))
   `(ediff-fine-diff-face-Ancestor ((,class (:background "Green" :foreground "Black"))))
   `(ediff-fine-diff-face-B ((,class (:background "cyan" :foreground "Black"))))
   `(ediff-fine-diff-face-C ((,class (:background "Turquoise" :foreground "Black"))))
   `(ediff-odd-diff-face-A ((,class (:background "Grey" :foreground "White"))))
   `(ediff-odd-diff-face-Ancestor ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-odd-diff-face-B ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-odd-diff-face-C ((,class (:background "Grey" :foreground "White"))))
   `(eieio-custom-slot-tag-face ((,class (:foreground "light blue"))))
   `(eldoc-highlight-function-argument ((,class (:bold t :weight bold :foreground "#00CC00" :background "black"))))
   `(emacs-wiki-bad-link-face ((,class (:bold t :foreground "red" :weight bold))))
   `(emacs-wiki-link-face ((,class (:bold t :foreground "green" :weight bold))))
   `(erc-action-face ((,class (:bold t :weight semi-bold))))
   `(erc-bold-face ((,class (:bold t :weight bold))))
   `(erc-current-nick-face ((,class (:bold t :foreground "LightSeaGreen" :weight semi-bold))))
   `(erc-dangerous-host-face ((,class (:foreground "red"))))
   `(erc-default-face ((,class (nil))))
   `(erc-direct-msg-face ((,class (:foreground "IndianRed"))))
   `(erc-error-face ((,class (:bold t :background "darkblue" :foreground "#00CC00" :weight semi-bold))))
   `(erc-fool-face ((,class (:foreground "dim gray"))))
   `(erc-highlight-face ((,class (:bold t :foreground "pale green" :weight bold))))
   `(erc-host-danger-face ((,class (:foreground "red"))))
   `(erc-input-face ((,class (:foreground "springgreen"))))
   `(erc-inverse-face ((,class (:bold t :background "Darkgreen" :foreground "Black" :weight semi-bold))))
   `(erc-keyword-face ((,class (:bold t :foreground "pale green" :weight bold))))
   `(erc-nick-default-face ((,class (:bold t :weight semi-bold))))
   `(erc-nick-msg-face ((,class (:bold t :foreground "springgreen" :weight semi-bold))))
   `(erc-notice-face ((,class (:foreground "seagreen" :weight normal))))
   `(erc-pal-face ((,class (:bold t :foreground "Magenta" :weight bold))))
   `(erc-prompt-face ((,class (:bold t :background "lightBlue2" :foreground "Black" :weight semi-bold))))
   `(erc-timestamp-face ((,class (:foreground "seagreen" :weight normal))))
   `(erc-underline-face ((,class (:underline t))))
   `(escape-glyph ((,class (:foreground "cyan"))))
   `(eshell-ls-archive-face ((,class (:bold t :foreground "Orchid" :weight bold))))
   `(eshell-ls-backup-face ((,class (:foreground "OrangeRed"))))
   `(eshell-ls-clutter-face ((,class (:bold t :foreground "OrangeRed" :weight bold))))
   `(eshell-ls-directory-face ((,class (:bold t :foreground "Blue" :weight bold))))
   `(eshell-ls-executable-face ((,class (:bold t :foreground "ForestGreen" :weight bold))))
   `(eshell-ls-missing-face ((,class (:bold t :foreground "Red" :weight bold))))
   `(eshell-ls-picture-face ((,class (:foreground "Violet"))))
   `(eshell-ls-product-face ((,class (:foreground "OrangeRed"))))
   `(eshell-ls-readonly-face ((,class (:foreground "Brown"))))
   `(eshell-ls-special-face ((,class (:bold t :foreground "Magenta" :weight bold))))
   `(eshell-ls-symlink-face ((,class (:bold t :foreground "DarkCyan" :weight bold))))
   `(eshell-ls-text-face ((,class (:foreground "medium aquamarine"))))
   `(eshell-ls-todo-face ((,class (:bold t :foreground "aquamarine" :weight bold))))
   `(eshell-ls-unreadable-face ((,class (:foreground "Grey30"))))
   `(eshell-prompt-face ((,class (:bold t :foreground "Red" :weight bold))))
   `(eshell-test-failed-face ((,class (:bold t :foreground "OrangeRed" :weight bold))))
   `(eshell-test-ok-face ((,class (:bold t :foreground "Green" :weight bold))))
   `(excerpt ((,class (:italic t :slant italic))))
   `(extra-whitespace-face ((,class (:background "pale green"))))
   `(face-1 ((,class (:stipple nil :foreground "royal blue" :family "andale mono"))))
   `(face-2 ((,class (:stipple nil :foreground "DeepSkyBlue1" :overline nil :underline nil :slant normal :foundry "outline" :family "andale mono"))))
   `(face-3 ((,class (:stipple nil :foreground "NavajoWhite3"))))
   `(ff-paths-non-existant-file-face ((,class (:bold t :foreground "NavyBlue" :weight bold))))
   `(ffap ((,class (:foreground "#00CC00" :background "darkgreen"))))
   `(fg:black ((,class (:foreground "black"))))
   `(fg:erc-color-face0 ((,class (:foreground "White"))))
   `(fg:erc-color-face1 ((,class (:foreground "black"))))
   `(fg:erc-color-face10 ((,class (:foreground "lightblue1"))))
   `(fg:erc-color-face11 ((,class (:foreground "cyan"))))
   `(fg:erc-color-face12 ((,class (:foreground "blue"))))
   `(fg:erc-color-face13 ((,class (:foreground "deeppink"))))
   `(fg:erc-color-face14 ((,class (:foreground "gray50"))))
   `(fg:erc-color-face15 ((,class (:foreground "gray90"))))
   `(fg:erc-color-face2 ((,class (:foreground "blue4"))))
   `(fg:erc-color-face3 ((,class (:foreground "green4"))))
   `(fg:erc-color-face4 ((,class (:foreground "red"))))
   `(fg:erc-color-face5 ((,class (:foreground "brown"))))
   `(fg:erc-color-face6 ((,class (:foreground "purple"))))
   `(fg:erc-color-face7 ((,class (:foreground "orange"))))
   `(fg:erc-color-face8 ((,class (:foreground "yellow"))))
   `(fg:erc-color-face9 ((,class (:foreground "green"))))
   `(file-name-shadow ((,class (:foreground "grey50"))))
   `(fixed ((,class (:bold t :weight bold))))
   `(fixed-pitch ((,class (nil))))
   `(fl-comment-face ((,class (:foreground "medium purple"))))
   `(fl-doc-string-face ((,class (:foreground "purple"))))
   `(fl-function-name-face ((,class (:foreground "green"))))
   `(fl-keyword-face ((,class (:foreground "LightGreen"))))
   `(fl-string-face ((,class (:foreground "light coral"))))
   `(fl-type-face ((,class (:foreground "cyan"))))
   `(flash-paren-face-off ((,class (nil))))
   `(flash-paren-face-on ((,class (nil))))
   `(flash-paren-face-region ((,class (nil))))
   `(flyspell-duplicate-face ((,class (:bold t :foreground "Gold3" :underline t :weight bold))))
   `(flyspell-incorrect-face ((,class (:bold t :foreground "OrangeRed" :underline t :weight bold))))
   `(font-latex-bold-face ((,class (:bold t :weight bold))))
   `(font-latex-italic-face ((,class (:italic t :slant italic))))
   `(font-latex-math-face ((,class (:foreground "burlywood"))))
   `(font-latex-sedate-face ((,class (:foreground "LightGray"))))
   `(font-latex-string-face ((,class (:bold t :background "black" :foreground "seagreen" :weight semi-bold))))
   `(font-latex-warning-face ((,class (:bold t :background "darkblue" :foreground "#00CC00" :weight semi-bold))))
   `(font-lock-builtin-face ((,class (:italic t :foreground "wheat" :slant italic))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "skyblue"))))
   `(font-lock-comment-face ((,class (:foreground "skyblue"))))
   `(font-lock-constant-face ((,class (:foreground "#ffa0a0"))))
   `(font-lock-doc-face ((,class (:bold t  :foreground "darkkhaki" :weight semi-bold))))
   `(font-lock-doc-string-face ((,class (:foreground "darkkhaki"))))
   `(font-lock-emphasized-face ((,class (:bold t :weight bold))))
   `(font-lock-exit-face ((,class (:foreground "green"))))
   `(font-lock-function-name-face ((,class (:bold t :foreground "sandybrown" :weight bold))))
   `(font-lock-keyword-face ((,class (:bold t :foreground "goldenrod" :weight semi-bold))))
   `(font-lock-negation-char-face ((,class (nil))))
   `(font-lock-other-emphasized-face ((,class (:italic t :bold t :slant italic :weight bold))))
   `(font-lock-other-type-face ((,class (:bold t :foreground "green4" :weight bold))))
   `(font-lock-preprocessor-face ((,class (:foreground "indianred"))))
   `(font-lock-reference-face ((,class (:foreground "#777"))))
   `(font-lock-regexp-grouping-backslash ((,class (:bold t :weight bold :foreground "#00CC00" :background "black"))))
   `(font-lock-regexp-grouping-construct ((,class (:bold t :weight bold :foreground "#00CC00" :background "black"))))
   `(font-lock-special-comment-face ((,class (nil))))
   `(font-lock-special-keyword-face ((,class (:foreground "navajowhite"))))
   `(font-lock-string-face ((,class (:bold t :foreground "khaki" :weight semi-bold))))
   `(font-lock-type-face ((,class (:foreground "darkkhaki"))))
   `(font-lock-variable-name-face ((,class (:foreground "orchid"))))
   `(font-lock-warning-face ((,class (:bold t :background "orangered" :foreground "yellow2" :weight semi-bold))))
   `(fringe ((,class (:background "#151515" :foreground "#00CC00"))))
   `(gdb-arrow-face ((,class (:bold t :background "LightGreen" :foreground "black" :weight bold))))
   `(gnu-cite-face-3 ((,class (nil))))
   `(gnu-cite-face-4 ((,class (nil))))
   `(gnus-cite-attribution-face ((,class (:italic t :background "black" :foreground "#00CC00" :slant italic))))
   `(gnus-cite-face-1 ((,class (:background "black" :foreground "springgreen"))))
   `(gnus-cite-face-10 ((,class (nil))))
   `(gnus-cite-face-11 ((,class (nil))))
   `(gnus-cite-face-2 ((,class (:background "black" :foreground "lightseagreen"))))
   `(gnus-cite-face-3 ((,class (:background "black" :foreground "darkseagreen"))))
   `(gnus-cite-face-4 ((,class (:background "black" :foreground "forestgreen"))))
   `(gnus-cite-face-5 ((,class (:background "black" :foreground "springgreen"))))
   `(gnus-cite-face-6 ((,class (:background "black" :foreground "springgreen"))))
   `(gnus-cite-face-7 ((,class (:background "black" :foreground "springgreen"))))
   `(gnus-cite-face-8 ((,class (:background "black" :foreground "springgreen"))))
   `(gnus-cite-face-9 ((,class (:background "black" :foreground "springgreen"))))
   `(gnus-cite-face-list ((,class (:bold t :foreground "red" :weight bold))))
   `(gnus-emphasis-bold ((,class (:bold t :weight semi-bold))))
   `(gnus-emphasis-bold-italic ((,class (:italic t :bold t :slant italic :weight semi-bold))))
   `(gnus-emphasis-highlight-words ((,class (:bold t :background "black" :foreground "#00CC00" :underline t :weight bold))))
   `(gnus-emphasis-italic ((,class (:italic t :slant italic))))
   `(gnus-emphasis-strikethru ((,class (nil))))
   `(gnus-emphasis-underline ((,class (:underline t))))
   `(gnus-emphasis-underline-bold ((,class (:bold t :underline t :weight semi-bold))))
   `(gnus-emphasis-underline-bold-italic ((,class (:italic t :bold t :underline t :slant italic :weight semi-bold))))
   `(gnus-emphasis-underline-italic ((,class (:italic t :underline t :slant italic))))
   `(gnus-filterhist-face-1 ((,class (nil))))
   `(gnus-group-mail-1-empty-face ((,class (nil))))
   `(gnus-group-mail-1-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-group-mail-2-empty-face ((,class (nil))))
   `(gnus-group-mail-2-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-group-mail-3-empty-face ((,class (nil))))
   `(gnus-group-mail-3-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-group-mail-low-empty-face ((,class (nil))))
   `(gnus-group-mail-low-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-group-news-1-empty-face ((,class (nil))))
   `(gnus-group-news-1-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-group-news-2-empty-face ((,class (nil))))
   `(gnus-group-news-2-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-group-news-3-empty-face ((,class (nil))))
   `(gnus-group-news-3-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-group-news-4-empty-face ((,class (nil))))
   `(gnus-group-news-4-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-group-news-5-empty-face ((,class (nil))))
   `(gnus-group-news-5-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-group-news-6-empty-face ((,class (nil))))
   `(gnus-group-news-6-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-group-news-low-empty-face ((,class (nil))))
   `(gnus-group-news-low-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-header-content-face ((,class (:background "black" :foreground "springgreen"))))
   `(gnus-header-from-face ((,class (nil))))
   `(gnus-header-name-face ((,class (nil))))
   `(gnus-header-newsgroups-face ((,class (nil))))
   `(gnus-header-subject-face ((,class (nil))))
   `(gnus-picons-face ((,class (:background "white" :foreground "black"))))
   `(gnus-picons-xbm-face ((,class (:background "white" :foreground "black"))))
   `(gnus-server-agent-face ((,class (:bold t :foreground "PaleTurquoise" :weight bold))))
   `(gnus-server-closed-face ((,class (:italic t :foreground "Light Steel Blue" :slant italic))))
   `(gnus-server-denied-face ((,class (:bold t :foreground "Pink" :weight semi-bold))))
   `(gnus-server-offline-face ((,class (:bold t :foreground "Yellow" :weight bold))))
   `(gnus-server-opened-face ((,class (:bold t :foreground "Green1" :weight semi-bold))))
   `(gnus-signature-face ((,class (:background "black" :foreground "springgreen" :slant normal))))
   `(gnus-splash ((,class (:foreground "Brown"))))
   `(gnus-splash-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-summary-cancelled-face ((,class (:background "black" :foreground "#00CC00" :strike-through t))))
   `(gnus-summary-high-ancient-face ((,class (nil))))
   `(gnus-summary-high-read-face ((,class (nil))))
   `(gnus-summary-high-ticked-face ((,class (:bold t :background "black" :foreground "seagreen" :weight bold))))
   `(gnus-summary-high-undownloaded-face ((,class (:bold t :foreground "LightGray" :weight bold))))
   `(gnus-summary-high-unread-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-summary-low-ancient-face ((,class (nil))))
   `(gnus-summary-low-read-face ((,class (nil))))
   `(gnus-summary-low-ticked-face ((,class (nil))))
   `(gnus-summary-low-undownloaded-face ((,class (:italic t :foreground "LightGray" :slant italic :weight normal))))
   `(gnus-summary-low-unread-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-summary-normal-ancient-face ((,class (nil))))
   `(gnus-summary-normal-read-face ((,class (nil))))
   `(gnus-summary-normal-ticked-face ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(gnus-summary-normal-undownloaded-face ((,class (:foreground "LightGray" :weight normal))))
   `(gnus-summary-normal-unread-face ((,class (nil))))
   `(gnus-summary-selected-face ((,class (:background "#101010"))))
   `(gnus-x-face ((,class (:background "white" :foreground "black"))))
   `(green ((,class (:bold t :foreground "green" :weight bold))))
   `(gui-button-face ((,class (:background "grey75"))))
   `(gui-element ((,class (:background "Gray80"))))
   `(header-line ((,class (nil))))
   `(help-argument-name ((,class (:italic t :bold t :weight bold :slant oblique :foreground "#00CC00" :background "black"))))
   `(hi-black-b ((,class (:bold t :weight bold))))
   `(hi-black-hb ((,class (:bold t :underline nil :foreground "#00CC00" :background "black" :weight bold :height 1.67 :family "helv"))))
   `(hi-blue ((,class (:background "light blue"))))
   `(hi-blue-b ((,class (:bold t :foreground "blue" :weight bold))))
   `(hi-green ((,class (:background "green"))))
   `(hi-green-b ((,class (:bold t :foreground "green" :weight bold))))
   `(hi-pink ((,class (:background "pink"))))
   `(hi-red-b ((,class (:bold t :foreground "red" :weight bold))))
   `(hi-yellow ((,class (:background "yellow"))))
   `(highlight ((,class (:background "darkgreen" :foreground "#00CC00"))))
   `(highlight-changes-delete-face ((,class (:foreground "red" :underline t))))
   `(highlight-changes-face ((,class (:foreground "red"))))
   `(highline-face ((,class (:background "paleturquoise"))))
   `(highline-vertical-face ((,class (:background "lightcyan"))))
   `(holiday-face ((,class (:background "#000" :foreground "#777"))))
   `(horizontal-divider ((,class (:background "gray16" :foreground "#00ff00"))))
   `(hproperty:but-face ((,class (:bold t :background "wheat" :foreground "medium violet red" :weight bold))))
   `(hproperty:flash-face ((,class (:bold t :background "wheat" :foreground "gray80" :weight bold))))
   `(hproperty:highlight-face ((,class (:bold t :background "wheat" :foreground "red" :weight bold))))
   `(hproperty:item-face ((,class (:bold t :weight bold))))
   `(html-helper-bold-face ((,class (:bold t :weight bold))))
   `(html-helper-bold-italic-face ((,class (nil))))
   `(html-helper-builtin-face ((,class (:foreground "blue3" :underline t))))
   `(html-helper-italic-face ((,class (:italic t :slant italic))))
   `(html-helper-underline-face ((,class (:underline t))))
   `(html-tag-face ((,class (:bold t :weight bold))))
   `(hyper-apropos-documentation ((,class (:foreground "LightSalmon"))))
   `(hyper-apropos-heading ((,class (:bold t :weight bold))))
   `(hyper-apropos-hyperlink ((,class (:bold t :foreground "DodgerBlue1" :weight bold))))
   `(hyper-apropos-major-heading ((,class (:bold t :weight bold))))
   `(hyper-apropos-section-heading ((,class (:bold t :weight bold))))
   `(hyper-apropos-warning ((,class (:bold t :foreground "red" :weight bold))))
   `(ibuffer-deletion-face ((,class (:foreground "red"))))
   `(ibuffer-marked-face ((,class (:foreground "red"))))
   `(idlwave-help-link-face ((,class (:foreground "Blue"))))
   `(idlwave-shell-bp-face ((,class (:background "Pink" :foreground "Black"))))
   `(ido-first-match-face ((,class (:bold t :weight bold))))
   `(ido-indicator-face ((,class (:background "red" :foreground "yellow" :width condensed))))
   `(ido-only-match-face ((,class (:foreground "ForestGreen"))))
   `(ido-subdir-face ((,class (:foreground "red"))))
   `(info-header-node ((,class (:foreground "#666"))))
   `(info-header-xref ((,class (:foreground "#666"))))
   `(info-menu-5 ((,class (:underline t))))
   `(info-menu-6 ((,class (nil))))
   `(info-menu-header ((,class (:bold t :foreground "#666" :weight bold))))
   `(info-node ((,class (:bold t :foreground "#888" :weight bold))))
   `(info-xref ((,class (:bold t :foreground "#777" :weight bold))))
   `(isearch ((,class (:background "seagreen" :foreground "black"))))
   `(isearch-fail ((,class (:background "red4"))))
   `(isearch-secondary ((,class (:foreground "red3"))))
   `(ispell-face ((,class (:bold t :weight bold))))
   `(iswitchb-current-match ((,class (:bold t :weight bold :foreground "#00CC00" :background "black"))))
   `(iswitchb-invalid-regexp ((,class (:bold t :weight semi-bold :foreground "#00CC00" :background "darkblue"))))
   `(iswitchb-single-match ((,class (:foreground "medium spring green" :background "black"))))
   `(iswitchb-virtual-matches ((,class (:italic t :slant italic :foreground "seagreen1"))))
   `(italic ((,class (:italic t :bold t :background "black" :foreground "#00CC00" :slant oblique :weight bold))))
   `(jde-bug-breakpoint-cursor ((,class (:background "brown" :foreground "cyan"))))
   `(jde-bug-breakpoint-marker ((,class (:background "yellow" :foreground "red"))))
   `(jde-db-active-breakpoint-face ((,class (:background "red" :foreground "black"))))
   `(jde-db-requested-breakpoint-face ((,class (:background "yellow" :foreground "black"))))
   `(jde-db-spec-breakpoint-face ((,class (:background "green" :foreground "black"))))
   `(jde-java-font-lock-api-face ((,class (:foreground "light goldenrod"))))
   `(jde-java-font-lock-bold-face ((,class (:bold t :weight bold))))
   `(jde-java-font-lock-code-face ((,class (nil))))
   `(jde-java-font-lock-constant-face ((,class (:foreground "Aquamarine"))))
   `(jde-java-font-lock-doc-tag-face ((,class (:foreground "light coral"))))
   `(jde-java-font-lock-italic-face ((,class (:italic t :slant italic))))
   `(jde-java-font-lock-link-face ((,class (:foreground "cadetblue" :underline t :slant normal))))
   `(jde-java-font-lock-modifier-face ((,class (:foreground "LightSteelBlue"))))
   `(jde-java-font-lock-number-face ((,class (:foreground "LightSalmon"))))
   `(jde-java-font-lock-operator-face ((,class (:foreground "medium blue"))))
   `(jde-java-font-lock-package-face ((,class (:foreground "steelblue1"))))
   `(jde-java-font-lock-pre-face ((,class (nil))))
   `(jde-java-font-lock-underline-face ((,class (:underline t))))
   `(kai-gnus-cite-face-1 ((,class (:foreground "LightCyan4"))))
   `(kai-gnus-cite-face-2 ((,class (:foreground "LightSkyBlue2"))))
   `(kai-gnus-cite-face-3 ((,class (:foreground "DodgerBlue3"))))
   `(kai-gnus-group-mail-face ((,class (:foreground "darkslategrey"))))
   `(kai-gnus-group-nonempty-mail-face ((,class (:foreground "DarkRed"))))
   `(kai-gnus-group-starred-face ((,class (:foreground "grey50"))))
   `(lazy-highlight ((,class (:background "darkseagreen" :foreground "black"))))
   `(lazy-highlight-face ((,class (:bold t :foreground "dark magenta" :weight bold))))
   `(left-margin ((,class (:bold t :background "wheat" :foreground "black" :weight bold))))
   `(linemenu-face ((,class (:background "gray30"))))
   `(link ((,class (:foreground "cyan1" :underline t))))
   `(link-visited ((,class (:underline t :foreground "violet"))))
   `(list-mode-item-selected ((,class (:bold t :background "gray68" :foreground "black" :weight bold))))
   `(log-view-file-face ((,class (:bold t :background "grey70" :weight bold))))
   `(log-view-message-face ((,class (:foreground "light salmon"))))
   `(m4-face ((,class (:background "gray90" :foreground "orange3"))))
   `(magenta ((,class (:foreground "magenta"))))
   `(makefile-makepp-perl ((,class (:background "DarkBlue"))))
   `(makefile-shell ((,class (nil))))
   `(makefile-space ((,class (:background "hotpink"))))
   `(makefile-targets ((,class (:bold t :weight bold :foreground "#00CC00" :background "black"))))
   `(man-bold ((,class (:bold t :weight bold))))
   `(man-heading ((,class (:bold t :weight bold))))
   `(man-italic ((,class (:foreground "yellow"))))
   `(man-xref ((,class (:underline t))))
   `(match ((,class (:background "RoyalBlue3"))))
   `(menu ((,class (:bold t :background "black" :foreground "green" :box (:line-width -1 :color "#606060") :weight semi-bold :width normal :family "Arial"))))
   `(message-cited-text ((,class (:italic t :background "black" :foreground "#00CC00" :slant oblique))))
   `(message-header-cc ((,class (nil))))
   `(message-header-contents ((,class (:bold t :background "wheat" :foreground "black" :weight bold))))
   `(message-header-name ((,class (nil))))
   `(message-header-newsgroups ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(message-header-other ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(message-header-subject ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(message-header-to ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(message-header-xheader ((,class (nil))))
   `(message-headers ((,class (:bold t :background "wheat" :foreground "black" :weight bold))))
   `(message-highlighted-header-contents ((,class (:bold t :background "wheat" :foreground "blue" :weight bold))))
   `(message-mml ((,class (:italic t :bold t :background "black" :foreground "#00CC00" :slant oblique :weight bold))))
   `(message-separator ((,class (nil))))
   `(message-url ((,class (:bold t :foreground "pink" :weight bold))))
   `(minibuffer-prompt ((,class (:background "black" :foreground "seagreen"))))
   `(mmm-default-submode-face ((,class (:background "#c0c0c5"))))
   `(mmm-face ((,class (:background "black" :foreground "green"))))
   `(mode-line ((,class (:bold t :background "#c2bfa5" :foreground "black" :box (:line-width -1 :color "#606060") :weight semi-bold :height 1.0 :family "Arial"))))
   `(mode-line-buffer-id ((,class (:bold t :background "#000" :foreground "#555" :weight bold))))
   `(mode-line-emphasis ((,class (:bold t :weight bold))))
   `(mode-line-highlight ((,class (:box (:line-width 2 :color "grey40" :style released-button)))))
   `(mode-line-inactive ((,class (:bold t :background "#101010" :foreground "grey50" :box (:line-width -1 :color "#606060") :weight semi-bold :height 1.0 :family "Arial"))))
   `(modeline-mousable ((,class (:background "#000" :foreground "#555"))))
   `(modeline-mousable-minor-mode ((,class (:background "#000" :foreground "#555"))))
   `(mouse ((,class (:background "black"))))
   `(my-summary-highlight-face ((,class (:background "PaleTurquoise4" :foreground "White"))))
   `(my-tab-face ((,class (:background "SlateBlue1"))))
   `(my-url-face ((,class (:foreground "LightBlue"))))
   `(next-error ((,class (:foreground "black" :background "seagreen"))))
   `(nil ((,class (nil))))
   `(nobreak-space ((,class (:foreground "cyan" :underline t))))
   `(outline-1 ((,class (:bold t :weight bold :foreground "sandybrown"))))
   `(outline-2 ((,class (:bold t :weight bold :foreground "greenyellow"))))
   `(outline-3 ((,class (:foreground "gray20" :background "forestgreen"))))
   `(outline-4 ((,class (:foreground "light sea green" :underline t))))
   `(outline-5 ((,class (:italic t :slant italic :foreground "seagreen1"))))
   `(outline-6 ((,class (:foreground "plum"))))
   `(outline-7 ((,class (:foreground "gold4"))))
   `(outline-8 ((,class (:foreground "cyan4"))))
   `(p4-depot-added-face ((,class (:foreground "steelblue1"))))
   `(p4-depot-deleted-face ((,class (:foreground "red"))))
   `(p4-depot-unmapped-face ((,class (:foreground "grey90"))))
   `(p4-diff-change-face ((,class (:foreground "dark green"))))
   `(p4-diff-del-face ((,class (:bold t :weight bold))))
   `(p4-diff-file-face ((,class (:background "blue"))))
   `(p4-diff-head-face ((,class (:background "blue"))))
   `(p4-diff-ins-face ((,class (:foreground "steelblue1"))))
   `(paren-blink-off ((,class (:foreground "brown"))))
   `(paren-blink-on ((,class (:foreground "purple"))))
   `(paren-face ((,class (:background "black" :foreground "darkgreen"))))
   `(paren-face-match ((,class (:background "black" :foreground "springgreen"))))
   `(paren-face-mismatch ((,class (:background "black" :foreground "#00CC00" :strike-through t))))
   `(paren-face-no-match ((,class (:background "black" :foreground "red"))))
   `(paren-match ((,class (:background "gray68" :foreground "white"))))
   `(paren-mismatch ((,class (:background "DeepPink" :foreground "black"))))
   `(paren-mismatch-face ((,class (:bold t :weight bold))))
   `(paren-no-match-face ((,class (:bold t :weight bold))))
   `(pointer ((,class (:bold t :background "wheat" :foreground "red" :weight bold))))
   `(primary-selection ((,class (:bold t :background "medium sea green" :weight bold))))
   `(pulse-highlight-face ((,class (:background "#AAAA33"))))
   `(pulse-highlight-start-face ((,class (:background "#AAAA33"))))
   `(qt-classes-face ((,class (:foreground "Red"))))
   `(query-replace ((,class (:foreground "black" :background "seagreen"))))
   `(reb-match-0 ((,class (:background "lightblue"))))
   `(reb-match-1 ((,class (:background "aquamarine"))))
   `(reb-match-2 ((,class (:background "springgreen"))))
   `(reb-match-3 ((,class (:background "yellow"))))
   `(red ((,class (:bold t :foreground "red" :weight bold))))
   `(region ((,class (:background "seagreen" :foreground "black"))))
   `(right-margin ((,class (:bold t :background "wheat" :foreground "black" :weight bold))))
   `(rpm-spec-dir-face ((,class (:foreground "green"))))
   `(rpm-spec-doc-face ((,class (:foreground "magenta"))))
   `(rpm-spec-ghost-face ((,class (:foreground "red"))))
   `(rpm-spec-macro-face ((,class (:foreground "purple"))))
   `(rpm-spec-package-face ((,class (:foreground "red"))))
   `(rpm-spec-tag-face ((,class (:foreground "blue"))))
   `(rst-level-1-face ((,class (:background "darkgreen85"))))
   `(rst-level-2-face ((,class (:background "darkgreen78"))))
   `(rst-level-3-face ((,class (:background "darkgreen71"))))
   `(rst-level-4-face ((,class (:background "darkgreen64"))))
   `(rst-level-5-face ((,class (:background "darkgreen57"))))
   `(rst-level-6-face ((,class (:background "darkgreen50"))))
   `(ruler-mode-column-number-face ((,class (:stipple nil :background "grey76" :foreground "black" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
   `(ruler-mode-current-column-face ((,class (:bold t :stipple nil :background "grey76" :foreground "yellow" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight bold :width normal :foundry "outline" :family "andale mono"))))
   `(ruler-mode-default-face ((,class (:stipple nil :background "grey76" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
   `(ruler-mode-fill-column-face ((,class (:stipple nil :background "grey76" :foreground "red" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
   `(ruler-mode-margins-face ((,class (:stipple nil :background "grey64" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
   `(ruler-mode-tab-stop-face ((,class (:stipple nil :background "grey76" :foreground "steelblue" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
   `(scroll-bar ((,class (nil))))
   `(searchm-buffer ((,class (:bold t :weight bold))))
   `(searchm-button ((,class (:bold t :weight bold))))
   `(searchm-field ((,class (nil))))
   `(searchm-field-label ((,class (:bold t :weight bold))))
   `(searchm-highlight ((,class (:bold t :weight bold))))
   `(secondary-selection ((,class (:background "darkseagreen" :foreground "black"))))
   `(semantic-decoration-on-fileless-includes ((,class (:background "#009000"))))
   `(semantic-decoration-on-includes ((,class (nil))))
   `(semantic-decoration-on-private-members-face ((,class (:background "#200000"))))
   `(semantic-decoration-on-protected-members-face ((,class (:background "#000020"))))
   `(semantic-decoration-on-unknown-includes ((,class (:background "#900000"))))
   `(semantic-decoration-on-unparsed-includes ((,class (:background "#555500"))))
   `(semantic-dirty-token-face ((,class (:background "gray10"))))
   `(semantic-highlight-edits-face ((,class (:background "gray20"))))
   `(semantic-highlight-func-current-tag-face ((,class (:background "gray20"))))
   `(semantic-intangible-face ((,class (:foreground "gray25"))))
   `(semantic-read-only-face ((,class (:background "gray25"))))
   `(semantic-tag-boundary-face ((,class (:overline "cyan"))))
   `(semantic-unmatched-syntax-face ((,class (:underline "red"))))
   `(senator-intangible-face ((,class (:foreground "gray75"))))
   `(senator-momentary-highlight-face ((,class (:background "gray30"))))
   `(senator-read-only-face ((,class (:background "#664444"))))
   `(setnu-line-number-face ((,class (:italic t :background "White" :foreground "MediumPurple3" :slant italic))))
   `(sgml-comment-face ((,class (:foreground "grey60"))))
   `(sgml-doctype-face ((,class (:foreground "red"))))
   `(sgml-end-tag-face ((,class (:foreground "seagreen"))))
   `(sgml-entity-face ((,class (:foreground "indian red"))))
   `(sgml-ignored-face ((,class (:background "gray60" :foreground "gray40"))))
   `(sgml-ms-end-face ((,class (:foreground "green"))))
   `(sgml-ms-start-face ((,class (:foreground "green"))))
   `(sgml-pi-face ((,class (:foreground "lime green"))))
   `(sgml-sgml-face ((,class (:foreground "brown"))))
   `(sgml-short-ref-face ((,class (:foreground "deep sky blue"))))
   `(sgml-start-tag-face ((,class (:foreground "seagreen"))))
   `(sh-heredoc-face ((,class (:foreground "tan"))))
   `(shadow ((,class (:foreground "grey50"))))
   `(shell-input-face ((,class (:bold t :background "wheat" :foreground "blue" :weight bold))))
   `(shell-option-face ((,class (:bold t :background "wheat" :foreground "turquoise4" :weight bold))))
   `(shell-output-2-face ((,class (:bold t :background "wheat" :foreground "dark goldenrod" :weight bold))))
   `(shell-output-3-face ((,class (:bold t :background "wheat" :foreground "dark goldenrod" :weight bold))))
   `(shell-output-face ((,class (:bold t :background "wheat" :foreground "black" :weight bold))))
   `(shell-prompt-face ((,class (:bold t :background "wheat" :foreground "dark orchid" :weight bold))))
   `(show-block-face1 ((,class (:background "gray10"))))
   `(show-block-face2 ((,class (:background "gray15"))))
   `(show-block-face3 ((,class (:background "gray20"))))
   `(show-block-face4 ((,class (:background "gray25"))))
   `(show-block-face5 ((,class (:background "gray30"))))
   `(show-block-face6 ((,class (:background "gray35"))))
   `(show-block-face7 ((,class (:background "gray40"))))
   `(show-block-face8 ((,class (:background "gray45"))))
   `(show-block-face9 ((,class (:background "gray50"))))
   `(show-paren-match ((,class (:background "light slate blue" :foreground "white"))))
   `(show-paren-mismatch ((,class (:background "red" :foreground "white"))))
   `(show-tabs-space-face ((,class (:foreground "yellow"))))
   `(show-tabs-tab-face ((,class (:foreground "red"))))
   `(show-trailing-whitespace ((,class (:background "red" :foreground "blue"))))
   `(smerge-base-face ((,class (:foreground "red"))))
   `(smerge-markers-face ((,class (:background "grey85"))))
   `(smerge-mine-face ((,class (:foreground "Gray85"))))
   `(smerge-other-face ((,class (:foreground "darkgreen"))))
   `(special-string-face ((,class (:foreground "light green"))))
   `(speedbar-button-face ((,class (:foreground "light green"))))
   `(speedbar-directory-face ((,class (:foreground "light blue"))))
   `(speedbar-file-face ((,class (:foreground "snow"))))
   `(speedbar-highlight-face ((,class (:background "green" :foreground "blue"))))
   `(speedbar-selected-face ((,class (:foreground "tan" :underline t))))
   `(speedbar-separator-face ((,class (:background "blue" :foreground "white" :overline "gray"))))
   `(speedbar-tag-face ((,class (:foreground "goldenrod1"))))
   `(strokes-char-face ((,class (:background "lightgray"))))
   `(swbuff-current-buffer-face ((,class (:bold t :weight bold))))
   `(tabbar-button-face ((,class (:background "black" :foreground "#00cc00" :box (:line-width 2 :color "black" :style released-button)))))
   `(tabbar-default-face ((,class (:background "black" :foreground "#00cc00"))))
   `(tabbar-selected-face ((,class (:background "black" :foreground "springgreen" :box (:line-width 2 :color "black" :style released-button)))))
   `(tabbar-separator-face ((,class (:background "black" :foreground "#00cc00"))))
   `(tabbar-unselected-face ((,class (:background "black" :foreground "seagreen" :box (:line-width 2 :color "black" :style pressed-button)))))
   `(template-message-face ((,class (:bold t :weight bold))))
   `(term-black ((,class (:foreground "black"))))
   `(term-blackbg ((,class (:background "black"))))
   `(term-blue ((,class (:foreground "blue"))))
   `(term-blue-bold-face ((,class (:bold t :background "snow2" :foreground "blue" :weight bold))))
   `(term-blue-face ((,class (:foreground "blue"))))
   `(term-blue-inv-face ((,class (:background "blue"))))
   `(term-blue-ul-face ((,class (:background "snow2" :foreground "blue" :underline t))))
   `(term-bluebg ((,class (:background "blue"))))
   `(term-bold ((,class (:bold t :weight bold))))
   `(term-cyan ((,class (:foreground "cyan"))))
   `(term-cyan-bold-face ((,class (:bold t :background "snow2" :foreground "cyan" :weight bold))))
   `(term-cyan-face ((,class (:foreground "cyan"))))
   `(term-cyan-inv-face ((,class (:background "cyan"))))
   `(term-cyan-ul-face ((,class (:background "snow2" :foreground "cyan" :underline t))))
   `(term-cyanbg ((,class (:background "cyan"))))
   `(term-default ((,class (:background "gray80" :foreground "gray30" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "lucida console"))))
   `(term-default-bg ((,class (:foreground "#CCBB77"))))
   `(term-default-bg-inv ((,class (:foreground "#CCBB77"))))
   `(term-default-bold-face ((,class (:bold t :background "snow2" :foreground "darkslategray" :weight bold))))
   `(term-default-face ((,class (:background "snow2" :foreground "darkslategray"))))
   `(term-default-fg ((,class (:background "#000055"))))
   `(term-default-fg-inv ((,class (:background "#000055"))))
   `(term-default-inv-face ((,class (:background "darkslategray" :foreground "snow2"))))
   `(term-default-ul-face ((,class (:background "snow2" :foreground "darkslategray" :underline t))))
   `(term-green ((,class (:foreground "green"))))
   `(term-green-bold-face ((,class (:bold t :background "snow2" :foreground "green" :weight bold))))
   `(term-green-face ((,class (:foreground "green"))))
   `(term-green-inv-face ((,class (:background "green"))))
   `(term-green-ul-face ((,class (:background "snow2" :foreground "green" :underline t))))
   `(term-greenbg ((,class (:background "green"))))
   `(term-invisible ((,class (:foreground "#CCBB77"))))
   `(term-invisible-inv ((,class (:foreground "#CCBB77"))))
   `(term-magenta ((,class (:foreground "magenta"))))
   `(term-magenta-bold-face ((,class (:bold t :background "snow2" :foreground "magenta" :weight bold))))
   `(term-magenta-face ((,class (:foreground "magenta"))))
   `(term-magenta-inv-face ((,class (:background "magenta"))))
   `(term-magenta-ul-face ((,class (:background "snow2" :foreground "magenta" :underline t))))
   `(term-magentabg ((,class (:background "magenta"))))
   `(term-red ((,class (:foreground "red"))))
   `(term-red-bold-face ((,class (:bold t :background "snow2" :foreground "red" :weight bold))))
   `(term-red-face ((,class (:foreground "red"))))
   `(term-red-inv-face ((,class (:background "red"))))
   `(term-red-ul-face ((,class (:background "snow2" :foreground "red" :underline t))))
   `(term-redbg ((,class (:background "red"))))
   `(term-underline ((,class (:underline t))))
   `(term-white ((,class (:foreground "white"))))
   `(term-white-bold-face ((,class (:bold t :background "snow2" :foreground "white" :weight bold))))
   `(term-white-face ((,class (:foreground "white"))))
   `(term-white-inv-face ((,class (:background "snow2"))))
   `(term-white-ul-face ((,class (:background "snow2" :foreground "white" :underline t))))
   `(term-whitebg ((,class (:background "white"))))
   `(term-yellow ((,class (:foreground "yellow"))))
   `(term-yellow-bold-face ((,class (:bold t :background "snow2" :foreground "yellow" :weight bold))))
   `(term-yellow-face ((,class (:foreground "yellow"))))
   `(term-yellow-inv-face ((,class (:background "yellow"))))
   `(term-yellow-ul-face ((,class (:background "snow2" :foreground "yellow" :underline t))))
   `(term-yellowbg ((,class (:background "yellow"))))
   `(tex-math-face ((,class (:foreground "RosyBrown"))))
   `(texinfo-heading-face ((,class (:foreground "Blue"))))
   `(text-cursor ((,class (:bold t :background "red" :foreground "wheat" :weight bold))))
   `(tool-bar ((,class (:background "#111" :foreground "#777" :box (:line-width 1 :style released-button)))))
   `(tooltip ((,class (nil))))
   `(trailing-whitespace ((,class (:background "lightseagreen" :foreground "black"))))
   `(underline ((,class (:bold t :foreground "#00CC00" :underline t :weight bold))))
   `(variable-pitch ((,class (:background "black" :foreground "#00CC00" :underline nil :family "Arial"))))
   `(vc-annotate-face-0046FF ((,class (:background "black" :foreground "wheat"))))
   `(vcursor ((,class (:background "cyan" :foreground "blue" :underline t))))
   `(vertical-border ((,class (nil))))
   `(vertical-divider ((,class (:bold t :weight bold))))
   `(vhdl-font-lock-attribute-face ((,class (:foreground "Orchid"))))
   `(vhdl-font-lock-directive-face ((,class (:foreground "CadetBlue"))))
   `(vhdl-font-lock-enumvalue-face ((,class (:foreground "Gold4"))))
   `(vhdl-font-lock-function-face ((,class (:foreground "Orchid4"))))
   `(vhdl-font-lock-generic-/constant-face ((,class (nil))))
   `(vhdl-font-lock-prompt-face ((,class (:bold t :foreground "Red" :weight bold))))
   `(vhdl-font-lock-reserved-words-face ((,class (:bold t :foreground "Orange" :weight bold))))
   `(vhdl-font-lock-translate-off-face ((,class (:background "LightGray"))))
   `(vhdl-font-lock-type-face ((,class (nil))))
   `(vhdl-font-lock-variable-face ((,class (nil))))
   `(vhdl-speedbar-architecture-face ((,class (:foreground "Blue"))))
   `(vhdl-speedbar-architecture-selected-face ((,class (:foreground "Blue" :underline t))))
   `(vhdl-speedbar-configuration-face ((,class (:foreground "DarkGoldenrod"))))
   `(vhdl-speedbar-configuration-selected-face ((,class (:foreground "DarkGoldenrod" :underline t))))
   `(vhdl-speedbar-entity-face ((,class (:foreground "ForestGreen"))))
   `(vhdl-speedbar-entity-selected-face ((,class (:foreground "ForestGreen" :underline t))))
   `(vhdl-speedbar-instantiation-face ((,class (:foreground "Brown"))))
   `(vhdl-speedbar-instantiation-selected-face ((,class (:foreground "Brown" :underline t))))
   `(vhdl-speedbar-package-face ((,class (:foreground "Grey50"))))
   `(vhdl-speedbar-package-selected-face ((,class (:foreground "Grey50" :underline t))))
   `(vhdl-speedbar-subprogram-face ((,class (nil))))
   `(viper-minibuffer-emacs-face ((,class (:background "darkseagreen2" :foreground "Black"))))
   `(viper-minibuffer-insert-face ((,class (:background "pink" :foreground "Black"))))
   `(viper-minibuffer-vi-face ((,class (:background "grey" :foreground "DarkGreen"))))
   `(viper-replace-overlay-face ((,class (:background "darkseagreen2" :foreground "Black"))))
   `(viper-search-face ((,class (:background "khaki" :foreground "Black"))))
   `(vm-header-content-face ((,class (:italic t :foreground "wheat" :slant italic))))
   `(vm-header-from-face ((,class (:italic t :foreground "wheat" :slant italic))))
   `(vm-header-name-face ((,class (:foreground "cyan"))))
   `(vm-header-subject-face ((,class (:foreground "cyan"))))
   `(vm-header-to-face ((,class (:italic t :foreground "cyan" :slant italic))))
   `(vm-message-cited-face ((,class (:foreground "Gray80"))))
   `(vm-monochrome-image ((,class (:background "white" :foreground "gray30"))))
   `(vm-summary-face-1 ((,class (:foreground "MediumAquamarine"))))
   `(vm-summary-face-2 ((,class (:foreground "MediumAquamarine"))))
   `(vm-summary-face-3 ((,class (:foreground "MediumAquamarine"))))
   `(vm-summary-face-4 ((,class (:foreground "MediumAquamarine"))))
   `(vm-summary-highlight-face ((,class (:foreground "White"))))
   `(vm-xface ((,class (:background "white" :foreground "black"))))
   `(vmpc-pre-sig-face ((,class (:foreground "forestgreen"))))
   `(vmpc-sig-face ((,class (:foreground "steelblue"))))
   `(vvb-face ((,class (:background "pink" :foreground "gray30"))))
   `(w3m-anchor ((,class (:bold t :foreground "DodgerBlue1" :weight bold))))
   `(w3m-arrived-anchor ((,class (:bold t :foreground "DodgerBlue3" :weight bold))))
   `(w3m-bold ((,class (:bold t :weight bold))))
   `(w3m-current-anchor ((,class (:bold t :underline t :weight bold))))
   `(w3m-form ((,class (:foreground "red" :underline t))))
   `(w3m-form-button ((,class (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
   `(w3m-form-button-mouse ((,class (:background "DarkSeaGreen1" :foreground "black" :box (:line-width 2 :style released-button)))))
   `(w3m-form-button-pressed ((,class (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
   `(w3m-header-line-location-content ((,class (:background "dark olive green" :foreground "wheat"))))
   `(w3m-header-line-location-title ((,class (:background "dark olive green" :foreground "beige"))))
   `(w3m-history-current-url ((,class (:background "SkyBlue4" :foreground "LightSkyBlue"))))
   `(w3m-image ((,class (:foreground "PaleGreen"))))
   `(w3m-image-anchor ((,class (:background "dark green"))))
   `(w3m-insert ((,class (:foreground "orchid"))))
   `(w3m-italic ((,class (:italic t :slant italic))))
   `(w3m-session-select ((,class (:foreground "white"))))
   `(w3m-session-selected ((,class (:bold t :foreground "white" :underline t :weight bold))))
   `(w3m-strike-through ((,class (:strike-through t))))
   `(w3m-tab-background ((,class (:background "LightSteelBlue" :foreground "black"))))
   `(w3m-tab-mouse ((,class (:background "Gray75" :foreground "white" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-selected ((,class (:background "Gray90" :foreground "black" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-selected-background ((,class (:background "LightSteelBlue" :foreground "black"))))
   `(w3m-tab-selected-retrieving ((,class (:background "Gray90" :foreground "red" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-unselected ((,class (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-unselected-retrieving ((,class (:background "Gray70" :foreground "OrangeRed" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-unselected-unseen ((,class (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
   `(w3m-underline ((,class (:underline t))))
   `(which-func ((,class (:foreground "Blue1"))))
   `(white ((,class (:foreground "white"))))
   `(widget ((,class (:background "gray75"))))
   `(widget-button ((,class (:bold t :background "black" :foreground "#00CC00" :weight bold))))
   `(widget-button-pressed ((,class (nil))))
   `(widget-documentation ((,class (nil))))
   `(widget-field ((,class (:italic t :bold t :background "black" :foreground "#00CC00" :slant oblique :weight bold))))
   `(widget-inactive ((,class (nil))))
   `(widget-single-line-field ((,class (nil))))
   `(woman-addition-face ((,class (:foreground "orange"))))
   `(woman-bold-face ((,class (:bold t :weight bold))))
   `(woman-italic-face ((,class (:italic t :foreground "beige" :slant italic :family "Arial"))))
   `(woman-unknown-face ((,class (:foreground "LightSalmon"))))
   `(x-face ((,class (:bold t :background "wheat" :foreground "black" :weight bold))))
   `(x-symbol-adobe-fontspecific-face ((,class (nil))))
   `(x-symbol-face ((,class (nil))))
   `(x-symbol-heading-face ((,class (:bold t :weight bold))))
   `(x-symbol-info-face ((,class (nil))))
   `(x-symbol-invisible-face ((,class (nil))))
   `(x-symbol-revealed-face ((,class (nil))))
   `(xrdb-option-name-face ((,class (:foreground "red"))))
   `(xref-keyword-face ((,class (:foreground "blue"))))
   `(xref-list-default-face ((,class (nil))))
   `(xref-list-pilot-face ((,class (:foreground "navy"))))
   `(xref-list-symbol-face ((,class (:foreground "navy"))))
   `(xsl-fo-alternate-face ((,class (:foreground "Yellow"))))
   `(xsl-fo-main-face ((,class (:foreground "PaleGreen"))))
   `(xsl-other-element-face ((,class (:foreground "Coral"))))
   `(xsl-xslt-alternate-face ((,class (:foreground "LightGray"))))
   `(xsl-xslt-main-face ((,class (:foreground "Wheat"))))
   `(xxml-emph-1-face ((,class (:background "lightyellow"))))
   `(xxml-emph-2-face ((,class (:background "lightyellow"))))
   `(xxml-header-1-face ((,class (:background "seashell1" :foreground "MediumAquamarine"))))
   `(xxml-header-2-face ((,class (:background "seashell1" :foreground "SkyBlue"))))
   `(xxml-header-3-face ((,class (:background "seashell1"))))
   `(xxml-header-4-face ((,class (:background "seashell1"))))
   `(xxml-interaction-face ((,class (:background "lightcyan"))))
   `(xxml-rug-face ((,class (:background "cyan"))))
   `(xxml-sparkle-face ((,class (:background "yellow"))))
   `(xxml-unbreakable-space-face ((,class (:foreground "grey" :underline t))))
   `(yellow ((,class (:bold t :foreground "yellow" :weight bold))))
   `(web-mode-css-prop-face ((,class (:foreground "violet"))))
   `(web-mode-css-psudo-class-face ((,class (:foreground "hot pink"))))
   `(web-mode-css-rule-face ((,class (:foreground "dark sea green"))))
   `(web-mode-html-attr-name-face ((,class (:foreground "pale green"))))
   `(web-mode-html-attr-cyan-face ((,class (:foreground "DarkSlateGray"))))
   `(web-mode-html-attr-value-face ((,class (:foreground "salmon"))))
   `(web-mode-html-tag-face ((,class (:foreground "SkyBlue1"))))
   `(web-mode-doctype-face ((,class (:foreground "darkslategray3"))))
   `(web-mode-variable-name-face ((,class (:foreground "OliveDrab1"))))
   `(zmacs-region ((,class (:bold t :background "lightyellow" :foreground "darkgreen" :weight bold))))))

(provide-theme 'desert)
