
(deftheme spring
  "A black on light green theme, to protect your eyes.")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'spring
   `(default ((,class (:background "#99bb99" :foreground "black"))))
   `(Info-title-1-face ((,class (:bold t :weight bold :height 1.728 :family "helv"))))
   `(Info-title-2-face ((,class (:bold t :weight bold :height 1.44 :family "helv"))))
   `(Info-title-3-face ((,class (:bold t :weight bold :height 1.2 :family "helv"))))
   `(Info-title-4-face ((,class (:bold t :weight bold :family "helv"))))
   `(OrangeRed ((,class (nil))))
   `(bbdb-company ((,class (nil))))
   `(bbdb-field-name ((,class (:bold t :weight bold))))
   `(bbdb-field-value ((,class (nil))))
   `(bbdb-name ((,class (:underline t))))
   `(bg:erc-color-face0 ((,class (nil))))
   `(bg:erc-color-face1 ((,class (nil))))
   `(bg:erc-color-face10 ((,class (nil))))
   `(bg:erc-color-face11 ((,class (nil))))
   `(bg:erc-color-face12 ((,class (nil))))
   `(bg:erc-color-face13 ((,class (nil))))
   `(bg:erc-color-face14 ((,class (nil))))
   `(bg:erc-color-face15 ((,class (nil))))
   `(bg:erc-color-face2 ((,class (nil))))
   `(bg:erc-color-face3 ((,class (nil))))
   `(bg:erc-color-face4 ((,class (nil))))
   `(bg:erc-color-face5 ((,class (nil))))
   `(bg:erc-color-face6 ((,class (nil))))
   `(bg:erc-color-face7 ((,class (nil))))
   `(bg:erc-color-face8 ((,class (nil))))
   `(bg:erc-color-face9 ((,class (nil))))
   `(blank-space-face ((,class (:background "LightGray"))))
   `(blank-tab-face ((,class (:background "cornsilk" :foreground "black"))))
   `(blue ((,class (:foreground "blue"))))
   `(bold ((,class (:bold t :weight bold))))
   `(bold-italic ((,class (:italic t :bold t :foreground "purple4" :slant italic :weight bold))))
   `(border ((,class (:background "black"))))
   `(border-glyph ((,class (nil))))
   `(buffer-menu-buffer ((,class (:bold t :weight bold))))
   `(buffers-tab ((,class (:background "gray75"))))
   `(button ((,class (:underline t))))
   `(c-nonbreakable-space-face ((,class (:bold t :background "#332200" :weight bold))))
   `(calendar-today-face ((,class (:underline t))))
   `(cmode-bracket-face ((,class (:bold t :weight bold))))
   `(color-mode-face-@ ((,class (:foreground "orange"))))
   `(color-mode-face-a ((,class (:foreground "blue"))))
   `(color-mode-face-b ((,class (:foreground "red"))))
   `(color-mode-face-c ((,class (:foreground "green3"))))
   `(color-mode-face-d ((,class (:background "red" :foreground "white"))))
   `(color-mode-face-e ((,class (:background "orange" :foreground "blue"))))
   `(color-mode-face-f ((,class (:background "blue" :foreground "yellow"))))
   `(color-mode-face-g ((,class (:background "lightblue" :foreground "brown"))))
   `(color-mode-face-h ((,class (:background "brown" :foreground "white"))))
   `(comint-highlight-input ((,class (:bold t :weight bold))))
   `(comint-highlight-prompt ((,class (:foreground "SaddleBrown"))))
   `(comint-input-face ((,class (:foreground "deepskyblue"))))
   `(compilation-column-number ((,class (:bold t :weight bold :foreground "PaleGreen"))))
   `(compilation-error ((,class (:bold t :weight bold :foreground "Pink"))))
   `(compilation-info ((,class (:bold t :foreground "DarkOliveGreen" :weight bold))))
   `(compilation-line-number ((,class (:foreground "red3"))))
   `(compilation-warning ((,class (:bold t :foreground "Orange" :weight bold))))
   `(completions-annotations ((,class (:italic t :slant italic :foreground "dark slate gray"))))
   `(completions-common-part ((,class (:family "Consolas" :foundry "microsoft" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "green" :background "gray12" :stipple nil :height 143))))
   `(completions-first-difference ((,class (:bold t :weight bold))))
   `(cparen-around-andor-face ((,class (:bold t :foreground "maroon" :weight bold))))
   `(cparen-around-begin-face ((,class (:foreground "maroon"))))
   `(cparen-around-conditional-face ((,class (:bold t :foreground "RoyalBlue" :weight bold))))
   `(cparen-around-define-face ((,class (:bold t :foreground "Blue" :weight bold))))
   `(cparen-around-lambda-face ((,class (:foreground "LightSeaGreen"))))
   `(cparen-around-letdo-face ((,class (:bold t :foreground "LightSeaGreen" :weight bold))))
   `(cparen-around-quote-face ((,class (:foreground "SaddleBrown"))))
   `(cparen-around-set!-face ((,class (:foreground "OrangeRed"))))
   `(cparen-around-syntax-rules-face ((,class (:foreground "Magenta"))))
   `(cparen-around-vector-face ((,class (:foreground "chocolate"))))
   `(cparen-binding-face ((,class (:foreground "ForestGreen"))))
   `(cparen-binding-list-face ((,class (:bold t :foreground "ForestGreen" :weight bold))))
   `(cparen-conditional-clause-face ((,class (:foreground "RoyalBlue"))))
   `(cparen-normal-paren-face ((,class (:foreground "grey50"))))
   `(cperl-array-face ((,class (:bold t :foreground "wheat" :weight bold))))
   `(cperl-hash-face ((,class (:italic t :bold t :foreground "chartreuse" :slant italic :weight bold))))
   `(cperl-nonoverridable-face ((,class (:foreground "aquamarine"))))
   `(cursor ((,class (:background "navy"))))
   `(custom-button-face ((,class (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
   `(custom-button-pressed-face ((,class (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
   `(custom-changed-face ((,class (:background "blue" :foreground "white"))))
   `(custom-comment-face ((,class (:background "dim gray"))))
   `(custom-comment-tag-face ((,class (:foreground "gray80"))))
   `(custom-documentation-face ((,class (nil))))
   `(custom-face-tag-face ((,class (:bold t :underline t :weight bold :height 1.2 :family "helv"))))
   `(custom-group-tag-face ((,class (:bold t :foreground "light blue" :underline t :weight bold :height 1.2))))
   `(custom-group-tag-face-1 ((,class (:bold t :foreground "pink" :underline t :weight bold :height 1.2 :family "helv"))))
   `(custom-invalid-face ((,class (:background "red" :foreground "yellow"))))
   `(custom-modified-face ((,class (:background "blue" :foreground "white"))))
   `(custom-rogue-face ((,class (:background "black" :foreground "pink"))))
   `(custom-saved-face ((,class (:underline t))))
   `(custom-set-face ((,class (:background "white" :foreground "blue"))))
   `(custom-state-face ((,class (:bold t :foreground "lime green" :weight bold))))
   `(custom-variable-button-face ((,class (:bold t :underline t :weight bold))))
   `(custom-variable-tag-face ((,class (:bold t :foreground "light blue" :underline t :weight bold :height 1.2 :family "helv"))))
   `(cvs-filename-face ((,class (:foreground "blue4"))))
   `(cvs-handled-face ((,class (:foreground "pink"))))
   `(cvs-header-face ((,class (:bold t :foreground "blue4" :weight bold))))
   `(cvs-marked-face ((,class (:bold t :foreground "green3" :weight bold))))
   `(cvs-msg-face ((,class (:italic t :slant italic))))
   `(cvs-need-action-face ((,class (:foreground "orange"))))
   `(cvs-unknown-face ((,class (:foreground "red"))))
   `(diary-face ((,class (:bold t :foreground "red" :weight bold))))
   `(sh-heredoc ((,class (:italic t :slant italic :foreground "orange4"))))
   `(sh-quoted-exec ((,class (:italic t :slant italic :foreground "DarkGreen"))))
   `(dired-directory ((,class (:bold t :weight bold :foreground "blue"))))
   `(dired-face-boring ((,class (:foreground "Gray65"))))
   `(dired-face-directory ((,class (:bold t :foreground "sky blue" :weight bold))))
   `(dired-face-executable ((,class (:foreground "green yellow"))))
   `(dired-face-flagged ((,class (:background "SlateGray" :foreground "tomato"))))
   `(dired-face-marked ((,class (:background "darkblue" :foreground "light salmon"))))
   `(dired-face-permissions ((,class (:foreground "aquamarine"))))
   `(dired-face-setuid ((,class (:foreground "Red"))))
   `(dired-face-socket ((,class (:foreground "magenta"))))
   `(dired-face-symlink ((,class (:foreground "grey95"))))
   `(dired-flagged ((,class (:bold t :weight bold :foreground "Pink"))))
   `(dired-header ((,class (:bold t :weight bold :foreground "OrangeRed3"))))
   `(dired-ignored ((,class (:foreground "grey40"))))
   `(dired-mark ((,class (:foreground "DarkGreen"))))
   `(dired-marked ((,class (:bold t :weight bold :foreground "red"))))
   `(dired-perm-write ((,class (:bold t :foreground "chocolate1" :weight bold))))
   `(dired-symlink ((,class (:bold t :weight bold :foreground "DarkMagenta"))))
   `(dired-warning ((,class (:bold t :weight bold :foreground "Pink"))))
   `(display-time-mail-balloon-enhance-face ((,class (:background "orange"))))
   `(display-time-mail-balloon-gnus-group-face ((,class (:foreground "blue"))))
   `(display-time-time-balloon-face ((,class (:foreground "red"))))
   `(ecb-bucket-token-face ((,class (:bold t :weight bold))))
   `(ecb-default-general-face ((,class (nil))))
   `(ecb-default-highlight-face ((,class (:background "cornflower blue" :foreground "yellow"))))
   `(ecb-directories-general-face ((,class (nil))))
   `(ecb-directory-face ((,class (:background "cornflower blue" :foreground "yellow"))))
   `(ecb-history-face ((,class (:background "cornflower blue" :foreground "yellow"))))
   `(ecb-history-general-face ((,class (nil))))
   `(ecb-method-face ((,class (:background "cornflower blue" :foreground "yellow"))))
   `(ecb-methods-general-face ((,class (nil))))
   `(ecb-source-face ((,class (:background "cornflower blue" :foreground "yellow"))))
   `(ecb-source-in-directories-buffer-face ((,class (:foreground "medium blue"))))
   `(ecb-sources-general-face ((,class (nil))))
   `(ecb-token-header-face ((,class (:background "SeaGreen1"))))
   `(ecb-type-token-class-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-enum-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-group-face ((,class (:bold t :foreground "dimgray" :weight bold))))
   `(ecb-type-token-interface-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-struct-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-typedef-face ((,class (:bold t :weight bold))))
   `(ediff-current-diff-face-A ((,class (:background "pale green" :foreground "firebrick"))))
   `(ediff-current-diff-face-Ancestor ((,class (:background "VioletRed" :foreground "Black"))))
   `(ediff-current-diff-face-B ((,class (:background "Yellow" :foreground "DarkOrchid"))))
   `(ediff-current-diff-face-C ((,class (:background "Pink" :foreground "Navy"))))
   `(ediff-even-diff-face-A ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-even-diff-face-Ancestor ((,class (:background "Grey" :foreground "White"))))
   `(ediff-even-diff-face-B ((,class (:background "Grey" :foreground "White"))))
   `(ediff-even-diff-face-C ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-fine-diff-face-A ((,class (:background "sky blue" :foreground "Navy"))))
   `(ediff-fine-diff-face-Ancestor ((,class (:background "Green" :foreground "Black"))))
   `(ediff-fine-diff-face-B ((,class (:background "cyan" :foreground "Black"))))
   `(ediff-fine-diff-face-C ((,class (:background "Turquoise" :foreground "Black"))))
   `(ediff-odd-diff-face-A ((,class (:background "Grey" :foreground "White"))))
   `(ediff-odd-diff-face-Ancestor ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-odd-diff-face-B ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-odd-diff-face-C ((,class (:background "Grey" :foreground "White"))))
   `(eieio-custom-slot-tag-face ((,class (:foreground "light blue"))))
   `(eldoc-highlight-function-argument ((,class (:bold t :weight bold))))
   `(emacs-wiki-bad-link-face ((,class (:bold t :foreground "red" :weight bold))))
   `(emacs-wiki-link-face ((,class (:bold t :foreground "green3" :weight bold))))
   `(erc-action-face ((,class (nil))))
   `(erc-bold-face ((,class (:bold t :weight bold))))
   `(erc-current-nick-face ((,class (:bold t :foreground "yellow" :weight bold))))
   `(erc-default-face ((,class (nil))))
   `(erc-direct-msg-face ((,class (:foreground "pale green"))))
   `(erc-error-face ((,class (:bold t :foreground "IndianRed" :weight bold))))
   `(erc-highlight-face ((,class (:bold t :foreground "pale green" :weight bold))))
   `(erc-input-face ((,class (:foreground "light blue"))))
   `(erc-inverse-face ((,class (:background "steel blue" :foreground "White"))))
   `(erc-keyword-face ((,class (:bold t :foreground "orange" :weight bold))))
   `(erc-notice-face ((,class (:foreground "light salmon"))))
   `(erc-pal-face ((,class (:foreground "pale green"))))
   `(erc-prompt-face ((,class (:bold t :background "black" :foreground "light blue" :weight bold))))
   `(erc-timestamp-face ((,class (:bold t :foreground "green4" :weight bold))))
   `(erc-underline-face ((,class (:underline t))))
   `(escape-glyph ((,class (:foreground "cyan"))))
   `(eshell-ls-archive-face ((,class (:bold t :foreground "medium purple" :weight bold))))
   `(eshell-ls-backup-face ((,class (:foreground "dim gray"))))
   `(eshell-ls-clutter-face ((,class (:bold t :foreground "dim gray" :weight bold))))
   `(eshell-ls-directory-face ((,class (:bold t :foreground "medium slate blue" :weight bold))))
   `(eshell-ls-executable-face ((,class (:bold t :foreground "aquamarine" :weight bold))))
   `(eshell-ls-missing-face ((,class (:bold t :foreground "black" :weight bold))))
   `(eshell-ls-picture-face ((,class (:foreground "violet"))))
   `(eshell-ls-product-face ((,class (:foreground "light steel blue"))))
   `(eshell-ls-readonly-face ((,class (:foreground "aquamarine"))))
   `(eshell-ls-special-face ((,class (:bold t :foreground "gold" :weight bold))))
   `(eshell-ls-symlink-face ((,class (:bold t :foreground "white" :weight bold))))
   `(eshell-ls-unreadable-face ((,class (:foreground "dim gray"))))
   `(eshell-prompt-face ((,class (:bold t :foreground "light sky blue" :weight bold))))
   `(eshell-test-failed-face ((,class (:bold t :foreground "OrangeRed" :weight bold))))
   `(eshell-test-ok-face ((,class (:bold t :foreground "Green" :weight bold))))
   `(excerpt ((,class (:italic t :slant italic))))
   `(extra-whitespace-face ((,class (:background "pale green"))))
   `(ff-paths-non-existant-file-face ((,class (:bold t :foreground "NavyBlue" :weight bold))))
   `(ffap ((,class (:foreground "yellow" :background "darkolivegreen"))))
   `(fg:black ((,class (:foreground "black"))))
   `(fg:erc-color-face0 ((,class (:foreground "white"))))
   `(fg:erc-color-face1 ((,class (:foreground "beige"))))
   `(fg:erc-color-face10 ((,class (:foreground "pale goldenrod"))))
   `(fg:erc-color-face11 ((,class (:foreground "light goldenrod yellow"))))
   `(fg:erc-color-face12 ((,class (:foreground "light yellow"))))
   `(fg:erc-color-face13 ((,class (:foreground "yellow"))))
   `(fg:erc-color-face14 ((,class (:foreground "light goldenrod"))))
   `(fg:erc-color-face15 ((,class (:foreground "lime green"))))
   `(fg:erc-color-face2 ((,class (:foreground "lemon chiffon"))))
   `(fg:erc-color-face3 ((,class (:foreground "light cyan"))))
   `(fg:erc-color-face4 ((,class (:foreground "powder blue"))))
   `(fg:erc-color-face5 ((,class (:foreground "sky blue"))))
   `(fg:erc-color-face6 ((,class (:foreground "dark sea green"))))
   `(fg:erc-color-face7 ((,class (:foreground "pale green"))))
   `(fg:erc-color-face8 ((,class (:foreground "medium spring green"))))
   `(fg:erc-color-face9 ((,class (:foreground "khaki"))))
   `(file-name-shadow ((,class (:foreground "grey50"))))
   `(fixed ((,class (:bold t :weight bold))))
   `(fixed-pitch ((,class (:family "courier"))))
   `(fl-comment-face ((,class (:foreground "pink"))))
   `(fl-doc-string-face ((,class (:foreground "purple"))))
   `(fl-function-name-face ((,class (:foreground "red"))))
   `(fl-keyword-face ((,class (:foreground "cadetblue"))))
   `(fl-string-face ((,class (:foreground "DarkGreen"))))
   `(fl-type-face ((,class (:foreground "yellow"))))
   `(flyspell-duplicate-face ((,class (:bold t :foreground "Gold3" :underline t :weight bold))))
   `(flyspell-incorrect-face ((,class (:bold t :foreground "OrangeRed" :underline t :weight bold))))
   `(font-latex-bold-face ((,class (:bold t :foreground "OliveDrab" :weight bold))))
   `(font-latex-italic-face ((,class (:italic t :foreground "OliveDrab" :slant italic))))
   `(font-latex-math-face ((,class (:foreground "burlywood"))))
   `(font-latex-sedate-face ((,class (:foreground "LightGray"))))
   `(font-latex-string-face ((,class (:foreground "RosyBrown"))))
   `(font-latex-warning-face ((,class (:bold t :foreground "Red" :weight bold))))
   `(font-lock-builtin-face ((,class (:italic t :foreground "magenta4" :slant italic))))
   `(font-lock-comment-delimiter-face ((,class (:bold t :weight bold :foreground "DarkSlateGray"))))
   `(font-lock-comment-face ((,class (:bold t :foreground "DarkSlateGray" :weight bold))))
   `(font-lock-constant-face ((,class (:foreground "orange4"))))
   `(font-lock-doc-face ((,class (:foreground "DarkSlateBlue"))))
   `(font-lock-doc-string-face ((,class (:foreground "#00C000"))))
   `(font-lock-exit-face ((,class (:foreground "sienna"))))
   `(font-lock-function-name-face ((,class (:bold t :foreground "DarkBlue" :weight bold))))
   `(font-lock-keyword-face ((,class (:bold t :foreground "MediumBlue" :weight bold))))
   `(font-lock-negation-char-face ((,class (nil))))
   `(font-lock-other-emphasized-face ((,class (:bold t :foreground "gold1" :weight bold))))
   `(font-lock-other-type-face ((,class (:bold t :foreground "gold1" :weight bold))))
   `(font-lock-preprocessor-face ((,class (:foreground "blue violet"))))
   `(font-lock-reference-face ((,class (:bold t :foreground "orangered" :weight bold))))
   `(font-lock-regexp-grouping-backslash ((,class (:bold t :weight bold))))
   `(font-lock-regexp-grouping-construct ((,class (:bold t :weight bold))))
   `(font-lock-string-face ((,class (:foreground "firebrick"))))
   `(font-lock-type-face ((,class (:bold t :foreground "maroon" :weight bold))))
   `(font-lock-variable-name-face ((,class (:foreground "purple4"))))
   `(font-lock-warning-face ((,class (:bold t :foreground "DarkRed" :weight bold))))
   `(fringe ((,class (:background "grey10"))))
   `(gnu-cite-face-3 ((,class (nil))))
   `(gnu-cite-face-4 ((,class (nil))))
   `(gnus-cite-attribution-face ((,class (:bold t :weight bold))))
   `(gnus-cite-face-1 ((,class (:foreground "LightSalmon"))))
   `(gnus-cite-face-10 ((,class (:foreground "medium purple"))))
   `(gnus-cite-face-11 ((,class (:foreground "turquoise"))))
   `(gnus-cite-face-2 ((,class (:foreground "Khaki"))))
   `(gnus-cite-face-3 ((,class (:foreground "Coral"))))
   `(gnus-cite-face-4 ((,class (:foreground "yellow green"))))
   `(gnus-cite-face-5 ((,class (:foreground "dark khaki"))))
   `(gnus-cite-face-6 ((,class (:foreground "bisque"))))
   `(gnus-cite-face-7 ((,class (:foreground "peru"))))
   `(gnus-cite-face-8 ((,class (:foreground "light coral"))))
   `(gnus-cite-face-9 ((,class (:foreground "plum"))))
   `(gnus-emphasis-bold ((,class (:bold t :weight bold))))
   `(gnus-emphasis-bold-italic ((,class (:italic t :bold t :slant italic :weight bold))))
   `(gnus-emphasis-highlight-words ((,class (:background "black" :foreground "yellow"))))
   `(gnus-emphasis-italic ((,class (:italic t :slant italic))))
   `(gnus-emphasis-underline ((,class (:underline t))))
   `(gnus-emphasis-underline-bold ((,class (:bold t :underline t :weight bold))))
   `(gnus-emphasis-underline-bold-italic ((,class (:italic t :bold t :underline t :slant italic :weight bold))))
   `(gnus-emphasis-underline-italic ((,class (:italic t :underline t :slant italic))))
   `(gnus-filterhist-face-1 ((,class (nil))))
   `(gnus-group-mail-1-empty-face ((,class (:foreground "White"))))
   `(gnus-group-mail-1-face ((,class (:bold t :foreground "White" :weight bold))))
   `(gnus-group-mail-2-empty-face ((,class (:foreground "light cyan"))))
   `(gnus-group-mail-2-face ((,class (:bold t :foreground "light cyan" :weight bold))))
   `(gnus-group-mail-3-empty-face ((,class (:foreground "LightBlue"))))
   `(gnus-group-mail-3-face ((,class (:bold t :foreground "LightBlue" :weight bold))))
   `(gnus-group-mail-low-empty-face ((,class (:foreground "Aquamarine"))))
   `(gnus-group-mail-low-face ((,class (:bold t :foreground "Aquamarine" :weight bold))))
   `(gnus-group-news-1-empty-face ((,class (:foreground "White"))))
   `(gnus-group-news-1-face ((,class (:bold t :foreground "White" :weight bold))))
   `(gnus-group-news-2-empty-face ((,class (:foreground "light cyan"))))
   `(gnus-group-news-2-face ((,class (:bold t :foreground "light cyan" :weight bold))))
   `(gnus-group-news-3-empty-face ((,class (:foreground "LightBlue"))))
   `(gnus-group-news-3-face ((,class (:bold t :foreground "LightBlue" :weight bold))))
   `(gnus-group-news-4-empty-face ((,class (:foreground "Aquamarine"))))
   `(gnus-group-news-4-face ((,class (:bold t :foreground "Aquamarine" :weight bold))))
   `(gnus-group-news-5-empty-face ((,class (:foreground "MediumAquamarine"))))
   `(gnus-group-news-5-face ((,class (:bold t :foreground "MediumAquamarine" :weight bold))))
   `(gnus-group-news-6-empty-face ((,class (:foreground "MediumAquamarine"))))
   `(gnus-group-news-6-face ((,class (:bold t :foreground "MediumAquamarine" :weight bold))))
   `(gnus-group-news-low-empty-face ((,class (:foreground "MediumAquamarine"))))
   `(gnus-group-news-low-face ((,class (:bold t :foreground "MediumAquamarine" :weight bold))))
   `(gnus-header-content-face ((,class (:foreground "LightSkyBlue3"))))
   `(gnus-header-from-face ((,class (:bold t :foreground "light cyan" :weight bold))))
   `(gnus-header-name-face ((,class (:bold t :foreground "LightBlue" :weight bold))))
   `(gnus-header-newsgroups-face ((,class (:bold t :foreground "MediumAquamarine" :weight bold))))
   `(gnus-header-subject-face ((,class (:bold t :foreground "light cyan" :weight bold))))
   `(gnus-picons-face ((,class (:background "white" :foreground "black"))))
   `(gnus-picons-xbm-face ((,class (:background "white" :foreground "black"))))
   `(gnus-signature-face ((,class (:italic t :foreground "Grey" :slant italic))))
   `(gnus-splash ((,class (:foreground "Brown"))))
   `(gnus-splash-face ((,class (:foreground "ForestGreen"))))
   `(gnus-summary-cancelled-face ((,class (:background "Black" :foreground "Yellow"))))
   `(gnus-summary-high-ancient-face ((,class (:bold t :foreground "MediumAquamarine" :weight bold))))
   `(gnus-summary-high-read-face ((,class (:bold t :foreground "Aquamarine" :weight bold))))
   `(gnus-summary-high-ticked-face ((,class (:bold t :foreground "LightSalmon" :weight bold))))
   `(gnus-summary-high-unread-face ((,class (:bold t :foreground "beige" :weight bold))))
   `(gnus-summary-low-ancient-face ((,class (:foreground "DimGray"))))
   `(gnus-summary-low-read-face ((,class (:foreground "slate gray"))))
   `(gnus-summary-low-ticked-face ((,class (:bold t :foreground "Pink" :weight bold))))
   `(gnus-summary-low-unread-face ((,class (:italic t :foreground "LightGray" :slant italic))))
   `(gnus-summary-normal-ancient-face ((,class (:foreground "MediumAquamarine"))))
   `(gnus-summary-normal-read-face ((,class (:foreground "Aquamarine"))))
   `(gnus-summary-normal-ticked-face ((,class (:bold t :foreground "LightSalmon" :weight bold))))
   `(gnus-summary-normal-unread-face ((,class (nil))))
   `(gnus-summary-selected-face ((,class (:background "DarkSlateBlue" :underline t))))
   `(gnus-x-face ((,class (:background "white" :foreground "black"))))
   `(green ((,class (:foreground "green4"))))
   `(gui-button-face ((,class (:background "grey75" :foreground "black"))))
   `(gui-element ((,class (:background "#e7e3d6" :foreground " #000000"))))
   `(header-line ((,class (:background "grey20" :foreground "grey90" :box nil))))
   `(help-argument-name ((,class (:italic t :slant italic :foreground "green4"))))
   `(highlight ((,class (:background "darkolivegreen" :foreground "yellow"))))
   `(highlight-changes-delete-face ((,class (:foreground "red" :underline t))))
   `(highlight-changes-face ((,class (:foreground "red"))))
   `(highline-face ((,class (:background "DeepSkyBlue4"))))
   `(holiday-face ((,class (:background "pink"))))
   `(html-helper-bold-face ((,class (:bold t :foreground "wheat" :weight bold))))
   `(html-helper-italic-face ((,class (:italic t :foreground "spring green" :slant italic))))
   `(html-helper-underline-face ((,class (:foreground "cornsilk" :underline t))))
   `(html-tag-face ((,class (:bold t :foreground "deep sky blue" :weight bold))))
   `(hyper-apropos-documentation ((,class (:foreground "darkred"))))
   `(hyper-apropos-heading ((,class (:bold t :weight bold))))
   `(hyper-apropos-hyperlink ((,class (:foreground "blue4"))))
   `(hyper-apropos-major-heading ((,class (:bold t :weight bold))))
   `(hyper-apropos-section-heading ((,class (:italic t :bold t :slant italic :weight bold))))
   `(hyper-apropos-warning ((,class (:bold t :foreground "red" :weight bold))))
   `(info-header-node ((,class (:italic t :bold t :foreground "white" :slant italic :weight bold))))
   `(info-header-xref ((,class (:bold t :foreground "cyan" :weight bold))))
   `(info-menu-5 ((,class (:foreground "red1" :underline t))))
   `(info-menu-6 ((,class (nil))))
   `(info-menu-header ((,class (:bold t :weight bold :family "helv"))))
   `(info-node ((,class (:italic t :bold t :foreground "white" :slant italic :weight bold))))
   `(info-xref ((,class (:bold t :foreground "blue" :weight bold))))
   `(isearch ((,class (:bold t :background "palevioletred2" :foreground "brown4" :weight bold))))
   `(isearch-fail ((,class (:background "red4"))))
   `(isearch-secondary ((,class (:foreground "red3"))))
   `(iswitchb-current-match ((,class (:bold t :weight bold :foreground "DarkRed"))))
   `(iswitchb-invalid-regexp ((,class (:bold t :weight bold :foreground "DarkSlateGrey"))))
   `(iswitchb-single-match ((,class (:bold t :weight bold :foreground "navy"))))
   `(iswitchb-virtual-matches ((,class (:italic t :slant italic :foreground "red3"))))
   `(italic ((,class (:italic t :foreground "OrangeRed4" :slant italic))))
   `(jde-bug-breakpoint-cursor ((,class (:background "brown" :foreground "cyan"))))
   `(jde-db-active-breakpoint-face ((,class (:background "red" :foreground "black"))))
   `(jde-db-requested-breakpoint-face ((,class (:background "yellow" :foreground "black"))))
   `(jde-db-spec-breakpoint-face ((,class (:background "green" :foreground "black"))))
   `(jde-java-font-lock-api-face ((,class (:foreground "light goldenrod"))))
   `(jde-java-font-lock-bold-face ((,class (:bold t :weight bold))))
   `(jde-java-font-lock-code-face ((,class (nil))))
   `(jde-java-font-lock-constant-face ((,class (:foreground "Aquamarine"))))
   `(jde-java-font-lock-doc-tag-face ((,class (:foreground "light coral"))))
   `(jde-java-font-lock-italic-face ((,class (:italic t :slant italic))))
   `(jde-java-font-lock-link-face ((,class (:foreground "blue" :underline t :slant normal))))
   `(jde-java-font-lock-modifier-face ((,class (:foreground "LightSteelBlue"))))
   `(jde-java-font-lock-number-face ((,class (:foreground "LightSalmon"))))
   `(jde-java-font-lock-operator-face ((,class (:foreground "medium blue"))))
   `(jde-java-font-lock-package-face ((,class (:foreground "steelblue1"))))
   `(jde-java-font-lock-pre-face ((,class (nil))))
   `(jde-java-font-lock-underline-face ((,class (:underline t))))
   `(kai-gnus-cite-face-1 ((,class (:foreground "LightCyan4"))))
   `(kai-gnus-cite-face-2 ((,class (:foreground "LightSkyBlue2"))))
   `(kai-gnus-cite-face-3 ((,class (:foreground "DodgerBlue3"))))
   `(kai-gnus-group-mail-face ((,class (:foreground "darkslategrey"))))
   `(kai-gnus-group-nonempty-mail-face ((,class (:foreground "DarkRed"))))
   `(kai-gnus-group-starred-face ((,class (:foreground "grey50"))))
   `(lazy-highlight ((,class (:background "paleturquoise4"))))
   `(lazy-highlight-face ((,class (:bold t :foreground "dark magenta" :weight bold))))
   `(left-margin ((,class (nil))))
   `(linemenu-face ((,class (:background "gray30"))))
   `(link ((,class (:foreground "maroon4" :underline t))))
   `(link-visited ((,class (:underline t :foreground "violet"))))
   `(list-mode-item-selected ((,class (:bold t :background "gray68" :foreground "yellow" :weight bold))))
   `(makefile-makepp-perl ((,class (:background "DarkBlue"))))
   `(makefile-shell ((,class (nil))))
   `(makefile-space ((,class (:background "hotpink"))))
   `(makefile-targets ((,class (:bold t :weight bold :foreground "MidnightBlue"))))
   `(match ((,class (:background "RoyalBlue3"))))
   `(menu ((,class (nil))))
   `(message-cited-text ((,class (:foreground "LightSalmon"))))
   `(message-header-cc ((,class (:bold t :foreground "light cyan" :weight bold))))
   `(message-header-contents ((,class (:italic t :slant italic))))
   `(message-header-name ((,class (:foreground "LightBlue"))))
   `(message-header-newsgroups ((,class (:bold t :foreground "MediumAquamarine" :weight bold))))
   `(message-header-other ((,class (:foreground "MediumAquamarine"))))
   `(message-header-subject ((,class (:bold t :foreground "light cyan" :weight bold))))
   `(message-header-to ((,class (:bold t :foreground "light cyan" :weight bold))))
   `(message-header-xheader ((,class (:foreground "MediumAquamarine"))))
   `(message-headers ((,class (:bold t :weight bold))))
   `(message-highlighted-header-contents ((,class (:italic t :bold t :slant italic :weight bold))))
   `(message-mml ((,class (:bold t :foreground "MediumSpringGreen" :weight bold))))
   `(message-separator ((,class (:foreground "chocolate"))))
   `(minibuffer-prompt ((,class (:foreground "blue"))))
   `(mode-line ((,class (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :height 1.0 :family "Arial"))))
   `(mode-line-buffer-id ((,class (:background "goldenrod" :foreground "darkblue"))))
   `(mode-line-emphasis ((,class (:bold t :weight bold))))
   `(mode-line-highlight ((,class (:box (:line-width 2 :color "grey40" :style released-button)))))
   `(mode-line-inactive ((,class (:background "dark slate blue" :foreground "wheat" :box (:line-width 1 :color "grey65" :style released-button) :height 1.0 :family "Arial"))))
   `(modeline-mousable ((,class (:background "goldenrod" :foreground "darkblue"))))
   `(modeline-mousable-minor-mode ((,class (:background "goldenrod" :foreground "darkblue"))))
   `(mouse ((,class (:background "yellow"))))
   `(my-tab-face ((,class (:background "SlateBlue1"))))
   `(next-error ((,class (:foreground "yellow" :background "blue3"))))
   `(nobreak-space ((,class (:foreground "cyan" :underline t))))
   `(outline-1 ((,class (:bold t :weight bold :foreground "DarkBlue"))))
   `(outline-2 ((,class (:bold t :weight bold :foreground "DarkMagenta"))))
   `(outline-3 ((,class (:italic t :slant italic :foreground "MidnightBlue"))))
   `(outline-4 ((,class (:foreground "MediumVioletRed"))))
   `(outline-5 ((,class (:foreground "OrangeRed4"))))
   `(outline-6 ((,class (:foreground "gold4"))))
   `(outline-7 ((,class (:foreground "green4"))))
   `(outline-8 ((,class (:foreground "DeepSkyBlue4"))))
   `(p4-depot-added-face ((,class (:foreground "steelblue1"))))
   `(p4-depot-deleted-face ((,class (:foreground "red"))))
   `(p4-depot-unmapped-face ((,class (:foreground "grey90"))))
   `(p4-diff-change-face ((,class (:foreground "dark green"))))
   `(p4-diff-del-face ((,class (:bold t :foreground "salmon" :weight bold))))
   `(p4-diff-file-face ((,class (:background "blue"))))
   `(p4-diff-head-face ((,class (:background "blue"))))
   `(p4-diff-ins-face ((,class (:foreground "steelblue1"))))
   `(paren-blink-off ((,class (:foreground "DodgerBlue4"))))
   `(paren-face-match ((,class (:background "turquoise"))))
   `(paren-face-mismatch ((,class (:background "purple" :foreground "white"))))
   `(paren-face-no-match ((,class (:background "yellow" :foreground "black"))))
   `(paren-match ((,class (:background "red" :foreground "yellow"))))
   `(paren-mismatch ((,class (:background "DeepPink"))))
   `(paren-mismatch-face ((,class (:bold t :weight bold))))
   `(paren-no-match-face ((,class (:bold t :weight bold))))
   `(pointer ((,class (:background "white"))))
   `(primary-selection ((,class (:bold t :background "medium sea green" :weight bold))))
   `(pulse-highlight-face ((,class (:background "#AAAA33"))))
   `(pulse-highlight-start-face ((,class (:background "#AAAA33"))))
   `(qt-classes-face ((,class (:foreground "Red"))))
   `(query-replace ((,class (:bold t :weight bold :foreground "brown4" :background "palevioletred2"))))
   `(red ((,class (:foreground "red"))))
   `(region ((,class (:background "blue3" :foreground "yellow"))))
   `(right-margin ((,class (nil))))
   `(rst-level-1-face ((,class (:background "darkgreen85"))))
   `(rst-level-2-face ((,class (:background "darkgreen78"))))
   `(rst-level-3-face ((,class (:background "darkgreen71"))))
   `(rst-level-4-face ((,class (:background "darkgreen64"))))
   `(rst-level-5-face ((,class (:background "darkgreen57"))))
   `(rst-level-6-face ((,class (:background "darkgreen50"))))
   `(scroll-bar ((,class (nil))))
   `(secondary-selection ((,class (:background "SkyBlue4" :foreground "sienna3"))))
   `(semantic-decoration-on-fileless-includes ((,class (:background "#009000"))))
   `(semantic-decoration-on-includes ((,class (nil))))
   `(semantic-decoration-on-private-members-face ((,class (:background "#200000"))))
   `(semantic-decoration-on-protected-members-face ((,class (:background "#000020"))))
   `(semantic-decoration-on-unknown-includes ((,class (:background "#900000"))))
   `(semantic-decoration-on-unparsed-includes ((,class (:background "#555500"))))
   `(semantic-dirty-token-face ((,class (:background "gray10"))))
   `(semantic-highlight-edits-face ((,class (:background "gray20"))))
   `(semantic-highlight-func-current-tag-face ((,class (:background "gray20"))))
   `(semantic-tag-boundary-face ((,class (:overline "cyan"))))
   `(semantic-unmatched-syntax-face ((,class (:underline "red"))))
   `(senator-intangible-face ((,class (:foreground "gray75"))))
   `(senator-momentary-highlight-face ((,class (:background "gray30"))))
   `(senator-read-only-face ((,class (:background "#664444"))))
   `(sgml-comment-face ((,class (:foreground "dark turquoise"))))
   `(sgml-doctype-face ((,class (:foreground "orange"))))
   `(sgml-end-tag-face ((,class (:foreground "greenyellow"))))
   `(sgml-entity-face ((,class (:foreground "gold"))))
   `(sgml-ignored-face ((,class (:background "gray60" :foreground "gray20"))))
   `(sgml-ms-end-face ((,class (:foreground "brown4"))))
   `(sgml-ms-start-face ((,class (:foreground "DarkOrange4"))))
   `(sgml-pi-face ((,class (:foreground "lime green"))))
   `(sgml-sgml-face ((,class (:foreground "yellow"))))
   `(sgml-short-ref-face ((,class (:foreground "deep sky blue"))))
   `(sgml-start-tag-face ((,class (:foreground "mediumspringgreen"))))
   `(shadow ((,class (:foreground "grey40"))))
   `(shell-option-face ((,class (:foreground "blue"))))
   `(shell-output-2-face ((,class (:foreground "darkseagreen"))))
   `(shell-output-3-face ((,class (:foreground "slategrey"))))
   `(shell-output-face ((,class (:foreground "palegreen"))))
   `(shell-prompt-face ((,class (:foreground "red"))))
   `(show-paren-match ((,class (:background "turquoise" :foreground "blue"))))
   `(show-paren-mismatch ((,class (:background "purple" :foreground "white"))))
   `(show-tabs-space-face ((,class (:foreground "yellow"))))
   `(show-tabs-tab-face ((,class (:foreground "red"))))
   `(show-trailing-whitespace ((,class (:background "red" :foreground "blue"))))
   `(speedbar-button-face ((,class (:foreground "DarkRed"))))
   `(speedbar-directory-face ((,class (:foreground "navy blue"))))
   `(speedbar-file-face ((,class (:foreground "medium violet red"))))
   `(speedbar-highlight-face ((,class (:background "sea green" :foreground "gold1"))))
   `(speedbar-selected-face ((,class (:foreground "red" :underline t))))
   `(speedbar-separator-face ((,class (:background "blue" :foreground "white" :overline "gray"))))
   `(speedbar-tag-face ((,class (:foreground "firebrick3"))))
   `(swbuff-current-buffer-face ((,class (:bold t :weight bold))))
   `(template-message-face ((,class (:bold t :weight bold))))
   `(term-black ((,class (:foreground "black"))))
   `(term-blackbg ((,class (:background "black"))))
   `(term-blue ((,class (:foreground "blue"))))
   `(term-bluebg ((,class (:background "blue"))))
   `(term-bold ((,class (:bold t :weight bold))))
   `(term-cyan ((,class (:foreground "cyan"))))
   `(term-cyanbg ((,class (:background "cyan"))))
   `(term-default ((,class (:stipple nil :background "DarkSlateGray" :foreground "palegreen" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "lucida sans typewriter"))))
   `(term-default-bg ((,class (nil))))
   `(term-default-bg-inv ((,class (nil))))
   `(term-default-fg ((,class (nil))))
   `(term-default-fg-inv ((,class (nil))))
   `(term-green ((,class (:foreground "green"))))
   `(term-greenbg ((,class (:background "green"))))
   `(term-invisible ((,class (nil))))
   `(term-invisible-inv ((,class (nil))))
   `(term-magenta ((,class (:foreground "magenta"))))
   `(term-magentabg ((,class (:background "magenta"))))
   `(term-red ((,class (:foreground "red"))))
   `(term-redbg ((,class (:background "red"))))
   `(term-underline ((,class (:underline t))))
   `(term-white ((,class (:foreground "white"))))
   `(term-whitebg ((,class (:background "white"))))
   `(term-yellow ((,class (:foreground "yellow"))))
   `(term-yellowbg ((,class (:background "yellow"))))
   `(text-cursor ((,class (:background "DarkGoldenrod1" :foreground "DodgerBlue4"))))
   `(tool-bar ((,class (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
   `(tooltip ((,class (:background "lightyellow" :foreground "black"))))
   `(trailing-whitespace ((,class (:background "red"))))
   `(underline ((,class (:underline t))))
   `(variable-pitch ((,class (:family "helv"))))
   `(vc-annotate-face-0046FF ((,class (:background "black" :foreground "wheat"))))
   `(vcursor ((,class (:background "cyan" :foreground "blue" :underline t))))
   `(vertical-border ((,class (nil))))
   `(vertical-divider ((,class (:background "#e7e3d6" :foreground "#000000"))))
   `(vhdl-font-lock-attribute-face ((,class (:foreground "Orchid"))))
   `(vhdl-font-lock-directive-face ((,class (:foreground "CadetBlue"))))
   `(vhdl-font-lock-enumvalue-face ((,class (:foreground "Gold4"))))
   `(vhdl-font-lock-function-face ((,class (:foreground "Orchid4"))))
   `(vhdl-font-lock-prompt-face ((,class (:bold t :foreground "Red" :weight bold))))
   `(vhdl-font-lock-reserved-words-face ((,class (:bold t :foreground "Orange" :weight bold))))
   `(vhdl-font-lock-translate-off-face ((,class (:background "LightGray"))))
   `(vhdl-speedbar-architecture-face ((,class (:foreground "Blue"))))
   `(vhdl-speedbar-architecture-selected-face ((,class (:foreground "Blue" :underline t))))
   `(vhdl-speedbar-configuration-face ((,class (:foreground "DarkGoldenrod"))))
   `(vhdl-speedbar-configuration-selected-face ((,class (:foreground "DarkGoldenrod" :underline t))))
   `(vhdl-speedbar-entity-face ((,class (:foreground "ForestGreen"))))
   `(vhdl-speedbar-entity-selected-face ((,class (:foreground "ForestGreen" :underline t))))
   `(vhdl-speedbar-instantiation-face ((,class (:foreground "Brown"))))
   `(vhdl-speedbar-instantiation-selected-face ((,class (:foreground "Brown" :underline t))))
   `(vhdl-speedbar-package-face ((,class (:foreground "Grey50"))))
   `(vhdl-speedbar-package-selected-face ((,class (:foreground "Grey50" :underline t))))
   `(viper-minibuffer-emacs-face ((,class (:background "darkseagreen2" :foreground "Black"))))
   `(viper-minibuffer-insert-face ((,class (:background "pink" :foreground "Black"))))
   `(viper-minibuffer-vi-face ((,class (:background "grey" :foreground "DarkGreen"))))
   `(viper-replace-overlay-face ((,class (:background "darkseagreen2" :foreground "Black"))))
   `(viper-search-face ((,class (:background "khaki" :foreground "Black"))))
   `(vvb-face ((,class (:background "pink" :foreground "black"))))
   `(w3m-anchor ((,class (:foreground "MediumBlue"))))
   `(w3m-arrived-anchor ((,class (:foreground "DarkMagenta"))))
   `(w3m-bold ((,class (:bold t :weight bold))))
   `(w3m-current-anchor ((,class (:bold t :underline t :weight bold))))
   `(w3m-form ((,class (:foreground "red" :underline t))))
   `(w3m-form-button ((,class (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
   `(w3m-form-button-mouse ((,class (:background "DarkSeaGreen1" :foreground "black" :box (:line-width 2 :style released-button)))))
   `(w3m-form-button-pressed ((,class (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
   `(w3m-header-line-location-content ((,class (:background "Gray20" :foreground "LightGoldenrod"))))
   `(w3m-header-line-location-title ((,class (:background "Gray20" :foreground "Cyan"))))
   `(w3m-history-current-url ((,class (:background "SkyBlue4" :foreground "LightSkyBlue"))))
   `(w3m-image ((,class (:foreground "sienna"))))
   `(w3m-image-anchor ((,class (:background "plum"))))
   `(w3m-insert ((,class (:foreground "orchid"))))
   `(w3m-italic ((,class (:italic t :slant italic))))
   `(w3m-session-select ((,class (:foreground "navy"))))
   `(w3m-session-selected ((,class (:bold t :foreground "maroon" :underline t :weight bold))))
   `(w3m-strike-through ((,class (:strike-through t))))
   `(w3m-tab-background ((,class (:background "LightSteelBlue" :foreground "black"))))
   `(w3m-tab-mouse ((,class (:background "Gray75" :foreground "white" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-selected ((,class (:background "Gray90" :foreground "black" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-selected-background ((,class (:background "LightSteelBlue" :foreground "black"))))
   `(w3m-tab-selected-retrieving ((,class (:background "Gray90" :foreground "red" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-unselected ((,class (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-unselected-retrieving ((,class (:background "Gray70" :foreground "OrangeRed" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-unselected-unseen ((,class (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
   `(w3m-underline ((,class (:underline t))))
   `(which-func ((,class (:foreground "Blue1"))))
   `(widget ((,class (:background "gray75"))))
   `(widget-button ((,class (:bold t :weight bold))))
   `(widget-button-pressed ((,class (:foreground "red"))))
   `(widget-documentation ((,class (:foreground "lime green"))))
   `(widget-field ((,class (:background "dim gray"))))
   `(widget-inactive ((,class (:foreground "light gray"))))
   `(widget-single-line-field ((,class (:background "dim gray"))))
   `(woman-bold-face ((,class (:bold t :foreground "sky blue" :weight bold))))
   `(woman-italic-face ((,class (:foreground "deep sky blue"))))
   `(woman-unknown-face ((,class (:foreground "LightSalmon"))))
   `(x-face ((,class (:background "white"))))
   `(xref-keyword-face ((,class (:foreground "blue"))))
   `(xref-list-pilot-face ((,class (:foreground "navy"))))
   `(xref-list-symbol-face ((,class (:foreground "navy"))))
   `(ac-completion-face ((,class (:foreground "MidnightBlue" :background "gray60"))))
   `(yellow ((,class (:foreground "yellow"))))
   `(web-mode-css-prop-face ((,class (:foreground "DarkViolet"))))
   `(web-mode-css-psudo-class-face ((,class (:foreground "DarkGreen"))))
   `(web-mode-css-rule-face ((,class (:foreground "orange4"))))
   `(web-mode-html-attr-name-face ((,class (:foreground "green4"))))
   `(web-mode-html-attr-cyan-face ((,class (:foreground "DarkSlateGray"))))
   `(web-mode-html-attr-value-face ((,class (:foreground "DarkRed"))))
   `(web-mode-html-tag-face ((,class (:foreground "blue"))))
   `(web-mode-doctype-face ((,class (:foreground "gray20"))))
   `(js3-external-variable-face ((,class (:foreground "magenta"))))
   `(zmacs-region ((,class (:background "white" :foreground "midnightblue"))))))

(provide-theme 'spring)
