(deftheme xemacs
  "A black on lightgray theme, like the default theme of xemacs.")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xemacs
   `(default ((,class (:background "gainsboro" :foreground "black"))))
   `(CUA-global-mark-face ((,class (:background "brown" :foreground "black"))))
   `(CUA-rectangle-face ((,class (:background "firebrick" :foreground "black"))))
   `(CUA-rectangle-noselect-face ((,class (:background "light coral" :foreground "black"))))
   `(OrangeRed ((,class (nil))))
   `(bbdb-company ((,class (nil))))
   `(bbdb-field-name ((,class (:bold t :weight bold))))
   `(bbdb-field-value ((,class (nil))))
   `(bbdb-name ((,class (:underline t))))
   `(bg:erc-color-face0 ((,class (:background "White"))))
   `(bg:erc-color-face1 ((,class (:background "black"))))
   `(bg:erc-color-face10 ((,class (:background "lightblue1"))))
   `(bg:erc-color-face11 ((,class (:background "cyan"))))
   `(bg:erc-color-face12 ((,class (:background "blue"))))
   `(bg:erc-color-face13 ((,class (:background "deeppink"))))
   `(bg:erc-color-face14 ((,class (:background "gray50"))))
   `(bg:erc-color-face15 ((,class (:background "gray90"))))
   `(bg:erc-color-face2 ((,class (:background "blue4"))))
   `(bg:erc-color-face3 ((,class (:background "green4"))))
   `(bg:erc-color-face4 ((,class (:background "red"))))
   `(bg:erc-color-face5 ((,class (:background "brown"))))
   `(bg:erc-color-face6 ((,class (:background "purple"))))
   `(bg:erc-color-face7 ((,class (:background "orange"))))
   `(bg:erc-color-face8 ((,class (:background "pink"))))
   `(bg:erc-color-face9 ((,class (:background "green"))))
   `(blank-space-face ((,class (nil))))
   `(blank-tab-face ((,class (nil))))
   `(blue ((,class (nil))))
   `(bold ((,class (:bold t :weight bold))))
   `(bold-italic ((,class (:italic t :bold t :slant italic :weight bold))))
   `(border ((,class (:background "black"))))
   `(border-glyph ((,class (nil))))
   `(buffer-menu-buffer ((,class (:bold t :weight bold))))
   `(buffers-tab ((,class (:background "gray75"))))
   `(button ((,class (:underline t))))
   `(c-nonbreakable-space-face ((,class (:bold t :background "#332200" :weight bold))))
   `(calendar-today-face ((,class (:underline t))))
   `(color-mode-face-@ ((,class (:foreground "orange"))))
   `(color-mode-face-a ((,class (:foreground "blue"))))
   `(color-mode-face-b ((,class (:foreground "red"))))
   `(color-mode-face-c ((,class (:foreground "green3"))))
   `(color-mode-face-d ((,class (:background "red" :foreground "white"))))
   `(color-mode-face-e ((,class (:background "orange" :foreground "blue"))))
   `(color-mode-face-f ((,class (:background "blue" :foreground "yellow"))))
   `(color-mode-face-g ((,class (:background "lightblue" :foreground "brown"))))
   `(color-mode-face-h ((,class (:background "brown" :foreground "white"))))
   `(comint-highlight-input ((,class (:bold t :weight bold))))
   `(comint-highlight-prompt ((,class (:foreground "dark red"))))
   `(comint-input-face ((,class (:foreground "deepskyblue"))))
   `(compilation-column-number ((,class (:bold t :weight bold :foreground "SteelBlue4"))))
   `(compilation-error ((,class (:bold t :weight bold :foreground "VioletRed"))))
   `(compilation-info ((,class (:bold t :foreground "Green3" :weight bold))))
   `(compilation-line-number ((,class (:foreground "DarkGoldenrod"))))
   `(compilation-warning ((,class (:bold t :foreground "Orange" :weight bold))))
   `(completions-annotations ((,class (nil))))
   `(completions-common-part ((,class (:family "Consolas" :foundry "microsoft" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "gainsboro" :stipple nil :height 143))))
   `(completions-first-difference ((,class (:bold t :weight bold))))
   `(cperl-array-face ((,class (:bold t :background "lightyellow2" :foreground "Blue" :weight bold))))
   `(cperl-hash-face ((,class (:bold t :background "lightyellow2" :foreground "Red" :weight bold))))
   `(cperl-nonoverridable-face ((,class (:foreground "chartreuse3"))))
   `(cursor ((,class (:background "grey15"))))
   `(custom-button-face ((,class (:bold t :foreground "white" :weight bold))))
   `(custom-button-pressed-face ((,class (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
   `(custom-changed-face ((,class (:background "blue" :foreground "white"))))
   `(custom-comment-face ((,class (:background "dim gray"))))
   `(custom-comment-tag-face ((,class (:foreground "gray80"))))
   `(custom-documentation-face ((,class (nil))))
   `(custom-face-tag-face ((,class (:foreground "white" :underline t))))
   `(custom-group-tag-face ((,class (:bold t :foreground "blue" :underline t :weight bold))))
   `(custom-group-tag-face-1 ((,class (:foreground "red" :underline t))))
   `(custom-invalid-face ((,class (:background "red" :foreground "yellow"))))
   `(custom-modified-face ((,class (:background "blue" :foreground "white"))))
   `(custom-rogue-face ((,class (:background "black" :foreground "pink"))))
   `(custom-saved-face ((,class (:underline t))))
   `(custom-set-face ((,class (:background "white" :foreground "blue"))))
   `(custom-state-face ((,class (:foreground "dark green"))))
   `(custom-variable-button-face ((,class (:bold t :underline t :weight bold))))
   `(custom-variable-tag-face ((,class (:bold t :foreground "blue" :underline t :weight bold))))
   `(cvs-filename-face ((,class (:foreground "blue4"))))
   `(cvs-handled-face ((,class (:foreground "pale violet red"))))
   `(cvs-header-face ((,class (:bold t :foreground "blue4" :weight bold))))
   `(cvs-marked-face ((,class (:bold t :foreground "green3" :weight bold))))
   `(cvs-msg-face ((,class (nil))))
   `(cvs-need-action-face ((,class (:foreground "orange"))))
   `(cvs-unknown-face ((,class (:foreground "red"))))
   `(diary-face ((,class (:bold t :foreground "red" :weight bold))))
   `(dired-directory ((,class (:italic t :bold t :weight bold :slant italic :foreground "SlateBlue"))))
   `(dired-face-boring ((,class (:foreground "dark olive green"))))
   `(dired-face-directory ((,class (:bold t :foreground "forestgreen" :weight bold))))
   `(dired-face-executable ((,class (:foreground "indianred"))))
   `(dired-face-flagged ((,class (:background "SlateGray"))))
   `(dired-face-marked ((,class (:background "darkblue" :foreground "deepskyblue"))))
   `(dired-face-permissions ((,class (nil))))
   `(dired-face-setuid ((,class (:foreground "Red"))))
   `(dired-face-socket ((,class (:foreground "magenta"))))
   `(dired-face-symlink ((,class (:foreground "purple"))))
   `(dired-flagged ((,class (:bold t :weight bold :foreground "VioletRed"))))
   `(dired-header ((,class (:bold t :weight bold :foreground "SteelBlue4"))))
   `(dired-ignored ((,class (nil))))
   `(dired-mark ((,class (:foreground "OliveDrab"))))
   `(dired-marked ((,class (:bold t :weight bold :foreground "VioletRed"))))
   `(dired-perm-write ((,class (:foreground "RosyBrown4"))))
   `(dired-symlink ((,class (:bold t :weight bold :foreground "DarkBlue"))))
   `(dired-warning ((,class (:bold t :weight bold :foreground "VioletRed"))))
   `(display-time-mail-balloon-enhance-face ((,class (:background "orange"))))
   `(display-time-mail-balloon-gnus-group-face ((,class (:foreground "blue"))))
   `(display-time-time-balloon-face ((,class (:foreground "red"))))
   `(ecb-bucket-token-face ((,class (:bold t :weight bold))))
   `(ecb-default-general-face ((,class (nil))))
   `(ecb-default-highlight-face ((,class (:background "cornflower blue" :foreground "yellow"))))
   `(ecb-directories-general-face ((,class (nil))))
   `(ecb-directory-face ((,class (:background "cornflower blue" :foreground "yellow"))))
   `(ecb-history-face ((,class (:background "cornflower blue" :foreground "yellow"))))
   `(ecb-history-general-face ((,class (nil))))
   `(ecb-method-face ((,class (:background "cornflower blue" :foreground "yellow"))))
   `(ecb-methods-general-face ((,class (nil))))
   `(ecb-source-face ((,class (:background "cornflower blue" :foreground "yellow"))))
   `(ecb-source-in-directories-buffer-face ((,class (:foreground "medium blue"))))
   `(ecb-sources-general-face ((,class (nil))))
   `(ecb-token-header-face ((,class (:background "SeaGreen1"))))
   `(ecb-type-token-class-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-enum-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-group-face ((,class (:bold t :foreground "dimgray" :weight bold))))
   `(ecb-type-token-interface-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-struct-face ((,class (:bold t :weight bold))))
   `(ecb-type-token-typedef-face ((,class (:bold t :weight bold))))
   `(ediff-current-diff-face-A ((,class (:background "pale green" :foreground "firebrick"))))
   `(ediff-current-diff-face-Ancestor ((,class (:background "VioletRed" :foreground "Black"))))
   `(ediff-current-diff-face-B ((,class (:background "Yellow" :foreground "DarkOrchid"))))
   `(ediff-current-diff-face-C ((,class (:background "Pink" :foreground "Navy"))))
   `(ediff-even-diff-face-A ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-even-diff-face-Ancestor ((,class (:background "Grey" :foreground "White"))))
   `(ediff-even-diff-face-B ((,class (:background "Grey" :foreground "White"))))
   `(ediff-even-diff-face-C ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-fine-diff-face-A ((,class (:background "sky blue" :foreground "Navy"))))
   `(ediff-fine-diff-face-Ancestor ((,class (:background "Green" :foreground "Black"))))
   `(ediff-fine-diff-face-B ((,class (:background "cyan" :foreground "Black"))))
   `(ediff-fine-diff-face-C ((,class (:background "Turquoise" :foreground "Black"))))
   `(ediff-odd-diff-face-A ((,class (:background "Grey" :foreground "White"))))
   `(ediff-odd-diff-face-Ancestor ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-odd-diff-face-B ((,class (:background "light grey" :foreground "Black"))))
   `(ediff-odd-diff-face-C ((,class (:background "Grey" :foreground "White"))))
   `(eieio-custom-slot-tag-face ((,class (:foreground "blue"))))
   `(eldoc-highlight-function-argument ((,class (:bold t :weight bold))))
   `(emacs-wiki-bad-link-face ((,class (:bold t :foreground "red" :weight bold))))
   `(emacs-wiki-link-face ((,class (:bold t :foreground "green" :weight bold))))
   `(erc-action-face ((,class (:bold t :box (:line-width 2 :color "grey75") :weight bold))))
   `(erc-bold-face ((,class (:bold t :weight bold))))
   `(erc-default-face ((,class (nil))))
   `(erc-direct-msg-face ((,class (nil))))
   `(erc-error-face ((,class (:bold t :background "Red" :foreground "White" :weight bold))))
   `(erc-input-face ((,class (nil))))
   `(erc-inverse-face ((,class (nil))))
   `(erc-notice-face ((,class (nil))))
   `(erc-pal-face ((,class (nil))))
   `(erc-prompt-face ((,class (nil))))
   `(erc-timestamp-face ((,class (:bold t :foreground "green" :weight bold))))
   `(erc-underline-face ((,class (nil))))
   `(escape-glyph ((,class (:foreground "brown"))))
   `(eshell-ls-archive-face ((,class (:bold t :foreground "Orchid" :weight bold))))
   `(eshell-ls-backup-face ((,class (:foreground "OrangeRed"))))
   `(eshell-ls-clutter-face ((,class (:bold t :foreground "OrangeRed" :weight bold))))
   `(eshell-ls-directory-face ((,class (:bold t :foreground "Blue" :weight bold))))
   `(eshell-ls-executable-face ((,class (:bold t :foreground "ForestGreen" :weight bold))))
   `(eshell-ls-missing-face ((,class (:bold t :foreground "Red" :weight bold))))
   `(eshell-ls-picture-face ((,class (nil))))
   `(eshell-ls-product-face ((,class (:foreground "OrangeRed"))))
   `(eshell-ls-readonly-face ((,class (:foreground "Brown"))))
   `(eshell-ls-special-face ((,class (:bold t :foreground "Magenta" :weight bold))))
   `(eshell-ls-symlink-face ((,class (:bold t :foreground "DarkCyan" :weight bold))))
   `(eshell-ls-unreadable-face ((,class (:foreground "Grey30"))))
   `(eshell-prompt-face ((,class (:bold t :foreground "Red" :weight bold))))
   `(eshell-test-failed-face ((,class (:bold t :foreground "OrangeRed" :weight bold))))
   `(eshell-test-ok-face ((,class (:bold t :foreground "Green" :weight bold))))
   `(excerpt ((,class (nil))))
   `(ff-paths-non-existant-file-face ((,class (:bold t :foreground "NavyBlue" :weight bold))))
   `(ffap ((,class (:background "LightSkyBlue"))))
   `(fg:black ((,class (:foreground "black"))))
   `(fg:erc-color-face0 ((,class (:foreground "White"))))
   `(fg:erc-color-face1 ((,class (:foreground "black"))))
   `(fg:erc-color-face10 ((,class (:foreground "lightblue1"))))
   `(fg:erc-color-face11 ((,class (:foreground "cyan"))))
   `(fg:erc-color-face12 ((,class (:foreground "blue"))))
   `(fg:erc-color-face13 ((,class (:foreground "deeppink"))))
   `(fg:erc-color-face14 ((,class (:foreground "gray50"))))
   `(fg:erc-color-face15 ((,class (:foreground "gray90"))))
   `(fg:erc-color-face2 ((,class (:foreground "blue4"))))
   `(fg:erc-color-face3 ((,class (:foreground "green4"))))
   `(fg:erc-color-face4 ((,class (:foreground "red"))))
   `(fg:erc-color-face5 ((,class (:foreground "brown"))))
   `(fg:erc-color-face6 ((,class (:foreground "purple"))))
   `(fg:erc-color-face7 ((,class (:foreground "orange"))))
   `(fg:erc-color-face8 ((,class (:foreground "pink"))))
   `(fg:erc-color-face9 ((,class (:foreground "green"))))
   `(file-name-shadow ((,class (:foreground "dim gray"))))
   `(fixed ((,class (:bold t :weight bold))))
   `(fixed-pitch ((,class (:family "courier"))))
   `(fl-comment-face ((,class (:foreground "pink"))))
   `(fl-doc-string-face ((,class (:foreground "purple"))))
   `(fl-function-name-face ((,class (:foreground "red"))))
   `(fl-keyword-face ((,class (:foreground "cadetblue"))))
   `(fl-string-face ((,class (:foreground "green"))))
   `(fl-type-face ((,class (:foreground "dark magenta"))))
   `(flyspell-duplicate-face ((,class (:bold t :foreground "Gold3" :underline t :weight bold))))
   `(flyspell-incorrect-face ((,class (:bold t :foreground "OrangeRed" :underline t :weight bold))))
   `(font-latex-bold-face ((,class (nil))))
   `(font-latex-italic-face ((,class (nil))))
   `(font-latex-math-face ((,class (nil))))
   `(font-latex-sedate-face ((,class (nil))))
   `(font-latex-string-face ((,class (nil))))
   `(font-latex-warning-face ((,class (nil))))
   `(font-lock-builtin-face ((,class (:italic t :foreground "ForestGreen" :slant italic))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "IndianRed4"))))
   `(font-lock-comment-face ((,class (:foreground "yellow4"))))
   `(font-lock-constant-face ((,class (:foreground "OliveDrab"))))
   `(font-lock-doc-face ((,class (:foreground "green4"))))
   `(font-lock-doc-string-face ((,class (:bold t :foreground "blue4" :weight bold))))
   `(font-lock-exit-face ((,class (nil))))
   `(font-lock-function-name-face ((,class (:italic t :bold t :foreground "SlateBlue" :slant italic :weight bold))))
   `(font-lock-keyword-face ((,class (:bold t :foreground "DarkBlue" :weight bold))))
   `(font-lock-negation-char-face ((,class (nil))))
   `(font-lock-preprocessor-face ((,class (:foreground "blue3"))))
   `(font-lock-reference-face ((,class (:foreground "red3"))))
   `(font-lock-regexp-grouping-backslash ((,class (:bold t :weight bold))))
   `(font-lock-regexp-grouping-construct ((,class (:bold t :weight bold))))
   `(font-lock-string-face ((,class (:foreground "DarkRed"))))
   `(font-lock-type-face ((,class (:bold t :foreground "SteelBlue4" :weight bold))))
   `(font-lock-variable-name-face ((,class (:foreground "DarkGoldenrod"))))
   `(font-lock-warning-face ((,class (:bold t :foreground "VioletRed" :weight bold))))
   `(fringe ((,class (:background "LightSalmon4"))))
   `(gnu-cite-face-3 ((,class (nil))))
   `(gnu-cite-face-4 ((,class (nil))))
   `(gnus-cite-attribution-face ((,class (:italic t :bold t :slant italic :weight bold))))
   `(gnus-cite-face-1 ((,class (:foreground "MidnightBlue"))))
   `(gnus-cite-face-10 ((,class (:foreground "medium purple"))))
   `(gnus-cite-face-11 ((,class (:foreground "turquoise"))))
   `(gnus-cite-face-2 ((,class (:foreground "firebrick"))))
   `(gnus-cite-face-3 ((,class (:foreground "dark green"))))
   `(gnus-cite-face-4 ((,class (:foreground "OrangeRed"))))
   `(gnus-cite-face-5 ((,class (:foreground "dark khaki"))))
   `(gnus-cite-face-6 ((,class (:foreground "dark violet"))))
   `(gnus-cite-face-7 ((,class (:foreground "SteelBlue4"))))
   `(gnus-cite-face-8 ((,class (:foreground "magenta"))))
   `(gnus-cite-face-9 ((,class (:foreground "violet"))))
   `(gnus-emphasis-bold ((,class (:bold t :weight bold))))
   `(gnus-emphasis-bold-italic ((,class (:italic t :bold t :slant italic :weight bold))))
   `(gnus-emphasis-highlight-words ((,class (nil))))
   `(gnus-emphasis-italic ((,class (nil))))
   `(gnus-emphasis-underline ((,class (:background "goldenrod4" :foreground "white" :underline t))))
   `(gnus-emphasis-underline-bold ((,class (:bold t :background "yellow" :foreground "black" :underline t :weight bold))))
   `(gnus-emphasis-underline-bold-italic ((,class (:italic t :bold t :background "yellow" :foreground "black" :underline t :slant italic :weight bold))))
   `(gnus-emphasis-underline-italic ((,class (:italic t :background "yellow" :foreground "black" :underline t :slant italic))))
   `(gnus-filterhist-face-1 ((,class (nil))))
   `(gnus-group-mail-1-empty-face ((,class (:foreground "DeepPink3"))))
   `(gnus-group-mail-1-face ((,class (:bold t :foreground "DeepPink3" :weight bold))))
   `(gnus-group-mail-2-empty-face ((,class (:foreground "HotPink3"))))
   `(gnus-group-mail-2-face ((,class (:bold t :foreground "HotPink3" :weight bold))))
   `(gnus-group-mail-3-empty-face ((,class (:foreground "magenta4"))))
   `(gnus-group-mail-3-face ((,class (:bold t :foreground "magenta4" :weight bold))))
   `(gnus-group-mail-low-empty-face ((,class (:foreground "DeepPink4"))))
   `(gnus-group-mail-low-face ((,class (:bold t :foreground "DeepPink4" :weight bold))))
   `(gnus-group-news-1-empty-face ((,class (:foreground "ForestGreen"))))
   `(gnus-group-news-1-face ((,class (:bold t :foreground "ForestGreen" :weight bold))))
   `(gnus-group-news-2-empty-face ((,class (:foreground "CadetBlue4"))))
   `(gnus-group-news-2-face ((,class (:bold t :foreground "CadetBlue4" :weight bold))))
   `(gnus-group-news-3-empty-face ((,class (nil))))
   `(gnus-group-news-3-face ((,class (:bold t :foreground "tan" :weight bold))))
   `(gnus-group-news-4-empty-face ((,class (nil))))
   `(gnus-group-news-4-face ((,class (:bold t :foreground "white" :weight bold))))
   `(gnus-group-news-5-empty-face ((,class (nil))))
   `(gnus-group-news-5-face ((,class (:bold t :foreground "wheat" :weight bold))))
   `(gnus-group-news-6-empty-face ((,class (nil))))
   `(gnus-group-news-6-face ((,class (:bold t :foreground "tan" :weight bold))))
   `(gnus-group-news-low-empty-face ((,class (:foreground "DarkGreen"))))
   `(gnus-group-news-low-face ((,class (:bold t :foreground "DarkGreen" :weight bold))))
   `(gnus-header-content-face ((,class (:italic t :foreground "indianred4" :slant italic))))
   `(gnus-header-from-face ((,class (:bold t :foreground "red3" :weight bold))))
   `(gnus-header-name-face ((,class (:bold t :foreground "maroon" :weight bold))))
   `(gnus-header-newsgroups-face ((,class (:italic t :bold t :foreground "MidnightBlue" :slant italic :weight bold))))
   `(gnus-header-subject-face ((,class (:bold t :foreground "red4" :weight bold))))
   `(gnus-picons-face ((,class (:background "white" :foreground "black"))))
   `(gnus-picons-xbm-face ((,class (:background "white" :foreground "black"))))
   `(gnus-signature-face ((,class (nil))))
   `(gnus-splash ((,class (nil))))
   `(gnus-splash-face ((,class (:foreground "ForestGreen"))))
   `(gnus-summary-cancelled-face ((,class (:background "black" :foreground "yellow"))))
   `(gnus-summary-high-ancient-face ((,class (:bold t :foreground "RoyalBlue" :weight bold))))
   `(gnus-summary-high-read-face ((,class (:bold t :foreground "DarkGreen" :weight bold))))
   `(gnus-summary-high-ticked-face ((,class (:bold t :foreground "firebrick" :weight bold))))
   `(gnus-summary-high-unread-face ((,class (:bold t :weight bold))))
   `(gnus-summary-low-ancient-face ((,class (:italic t :foreground "RoyalBlue" :slant italic))))
   `(gnus-summary-low-read-face ((,class (:italic t :foreground "DarkGreen" :slant italic))))
   `(gnus-summary-low-ticked-face ((,class (:bold t :foreground "firebrick" :weight bold))))
   `(gnus-summary-low-unread-face ((,class (nil))))
   `(gnus-summary-normal-ancient-face ((,class (:foreground "RoyalBlue"))))
   `(gnus-summary-normal-read-face ((,class (:foreground "DarkGreen"))))
   `(gnus-summary-normal-ticked-face ((,class (:bold t :foreground "firebrick" :weight bold))))
   `(gnus-summary-normal-unread-face ((,class (:bold t :weight bold))))
   `(gnus-summary-selected-face ((,class (:background "deepskyblue4" :underline t))))
   `(gnus-x-face ((,class (:background "white" :foreground "black"))))
   `(green ((,class (nil))))
   `(gui-button-face ((,class (:background "grey75"))))
   `(gui-element ((,class (:background "Gray80"))))
   `(header-line ((,class (:background "grey20" :foreground "grey90" :box nil :overline "blueviolet" :underline "blueviolet"))))
   `(help-argument-name ((,class (:italic t :bold t :weight bold :slant italic))))
   `(highlight ((,class (:background "LightSkyBlue"))))
   `(highlight-changes-delete-face ((,class (:foreground "red" :underline t))))
   `(highlight-changes-face ((,class (:foreground "red"))))
   `(highline-face ((,class (:background "DarkOliveGreen3"))))
   `(holiday-face ((,class (:background "pink"))))
   `(html-helper-bold-face ((,class (:bold t :foreground "wheat" :weight bold))))
   `(html-helper-italic-face ((,class (nil))))
   `(html-helper-underline-face ((,class (:foreground "cornsilk" :underline t))))
   `(html-tag-face ((,class (:bold t :foreground "deep sky blue" :weight bold))))
   `(hyper-apropos-documentation ((,class (:foreground "darkred"))))
   `(hyper-apropos-heading ((,class (:bold t :weight bold))))
   `(hyper-apropos-hyperlink ((,class (:foreground "blue4"))))
   `(hyper-apropos-major-heading ((,class (:bold t :weight bold))))
   `(hyper-apropos-section-heading ((,class (:italic t :bold t :slant italic :weight bold))))
   `(hyper-apropos-warning ((,class (:bold t :foreground "red" :weight bold))))
   `(info-menu-5 ((,class (:underline t))))
   `(info-menu-6 ((,class (nil))))
   `(info-node ((,class (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
   `(info-xref ((,class (:bold t :foreground "deep pink" :weight bold))))
   `(isearch ((,class (:background "yellow"))))
   `(isearch-fail ((,class (:background "RosyBrown1"))))
   `(isearch-secondary ((,class (:foreground "red3"))))
   `(iswitchb-current-match ((,class (:italic t :bold t :weight bold :slant italic :foreground "SlateBlue"))))
   `(iswitchb-invalid-regexp ((,class (:bold t :weight bold :foreground "VioletRed"))))
   `(iswitchb-single-match ((,class (:foreground "grey55"))))
   `(iswitchb-virtual-matches ((,class (:italic t :slant italic :foreground "ForestGreen"))))
   `(italic ((,class (:italic t :bold t :slant italic :weight bold))))
   `(jde-bug-breakpoint-cursor ((,class (:background "brown" :foreground "cyan"))))
   `(jde-db-active-breakpoint-face ((,class (:background "red" :foreground "black"))))
   `(jde-db-requested-breakpoint-face ((,class (:background "yellow" :foreground "black"))))
   `(jde-db-spec-breakpoint-face ((,class (:background "green" :foreground "black"))))
   `(jde-java-font-lock-api-face ((,class (:foreground "light goldenrod"))))
   `(jde-java-font-lock-bold-face ((,class (:bold t :weight bold))))
   `(jde-java-font-lock-code-face ((,class (nil))))
   `(jde-java-font-lock-constant-face ((,class (:foreground "Aquamarine"))))
   `(jde-java-font-lock-doc-tag-face ((,class (:foreground "light coral"))))
   `(jde-java-font-lock-italic-face ((,class (:italic t :slant italic))))
   `(jde-java-font-lock-link-face ((,class (:foreground "blue" :underline t :slant normal))))
   `(jde-java-font-lock-modifier-face ((,class (:foreground "LightSteelBlue"))))
   `(jde-java-font-lock-number-face ((,class (:foreground "LightSalmon"))))
   `(jde-java-font-lock-operator-face ((,class (:foreground "medium blue"))))
   `(jde-java-font-lock-package-face ((,class (:foreground "steelblue1"))))
   `(jde-java-font-lock-pre-face ((,class (nil))))
   `(jde-java-font-lock-underline-face ((,class (:underline t))))
   `(kai-gnus-cite-face-1 ((,class (:foreground "LightCyan4"))))
   `(kai-gnus-cite-face-2 ((,class (:foreground "LightSkyBlue2"))))
   `(kai-gnus-cite-face-3 ((,class (:foreground "DodgerBlue3"))))
   `(kai-gnus-group-mail-face ((,class (:foreground "darkslategrey"))))
   `(kai-gnus-group-nonempty-mail-face ((,class (:foreground "DarkRed"))))
   `(kai-gnus-group-starred-face ((,class (:foreground "grey50"))))
   `(lazy-highlight ((,class (:background "paleturquoise4"))))
   `(lazy-highlight-face ((,class (:bold t :foreground "dark magenta" :weight bold))))
   `(left-margin ((,class (nil))))
   `(linemenu-face ((,class (nil))))
   `(link ((,class (:foreground "blue1" :underline t))))
   `(link-visited ((,class (:underline t :foreground "magenta4"))))
   `(list-mode-item-selected ((,class (nil))))
   `(makefile-makepp-perl ((,class (:background "LightBlue1"))))
   `(makefile-shell ((,class (nil))))
   `(makefile-space ((,class (:background "hotpink"))))
   `(makefile-targets ((,class (:italic t :bold t :weight bold :slant italic :foreground "SlateBlue"))))
   `(match ((,class (:background "yellow1"))))
   `(menu ((,class (nil))))
   `(message-cited-text ((,class (:foreground "red"))))
   `(message-header-cc ((,class (:bold t :foreground "MidnightBlue" :weight bold))))
   `(message-header-contents ((,class (:italic t :slant italic))))
   `(message-header-name ((,class (:foreground "cornflower blue"))))
   `(message-header-newsgroups ((,class (:italic t :bold t :foreground "blue4" :slant italic :weight bold))))
   `(message-header-other ((,class (:foreground "steel blue"))))
   `(message-header-subject ((,class (:bold t :foreground "navy blue" :weight bold))))
   `(message-header-to ((,class (:bold t :foreground "MidnightBlue" :weight bold))))
   `(message-header-xheader ((,class (:foreground "blue"))))
   `(message-headers ((,class (:bold t :weight bold))))
   `(message-highlighted-header-contents ((,class (:italic t :bold t :slant italic :weight bold))))
   `(message-mml ((,class (:bold t :foreground "ForestGreen" :weight bold))))
   `(message-separator ((,class (:foreground "brown"))))
   `(minibuffer-prompt ((,class (:foreground "dark magenta"))))
   `(mode-line ((,class (:background "white" :foreground "black" :box (:line-width -1 :style released-button) :height 1.0 :family "Arial"))))
   `(mode-line-buffer-id ((,class (:background "white" :foreground "black"))))
   `(mode-line-emphasis ((,class (:bold t :weight bold))))
   `(mode-line-highlight ((,class (:box (:line-width 2 :color "grey40" :style released-button)))))
   `(mode-line-inactive ((,class (:italic t :background "white" :foreground "cadetblue" :box (:line-width -1 :color "grey75") :overline "blueviolet" :underline "blueviolet" :slant oblique :weight light :height 1.0 :family "Arial"))))
   `(modeline-mousable ((,class (:background "white" :foreground "black"))))
   `(modeline-mousable-minor-mode ((,class (:background "white" :foreground "black"))))
   `(mouse ((,class (:background "grey15"))))
   `(next-error ((,class (:background "grey80"))))
   `(nobreak-space ((,class (:foreground "brown" :underline t))))
   `(outline-1 ((,class (:bold t :weight bold :foreground "SlateBlue"))))
   `(outline-2 ((,class (:italic t :slant italic :bold t :weight bold :foreground "DarkGoldenrod"))))
   `(outline-3 ((,class (:italic t :slant italic :foreground "DarkBlue"))))
   `(outline-4 ((,class (:italic t :slant italic :foreground "grey55"))))
   `(outline-5 ((,class (:foreground "SteelBlue4"))))
   `(outline-6 ((,class (:foreground "OliveDrab"))))
   `(outline-7 ((,class (:foreground "ForestGreen"))))
   `(outline-8 ((,class (:foreground "DarkRed"))))
   `(org-verbatim ((,class (:foreground "sienna"))))
   `(org-code ((,class (:foreground "DarkOliveGreen" :width narrow))))
   `(p4-depot-added-face ((,class (:foreground "blue"))))
   `(p4-depot-deleted-face ((,class (:foreground "red"))))
   `(p4-depot-unmapped-face ((,class (:foreground "grey30"))))
   `(p4-diff-change-face ((,class (:foreground "dark green"))))
   `(p4-diff-del-face ((,class (:foreground "red"))))
   `(p4-diff-file-face ((,class (:background "gray90"))))
   `(p4-diff-head-face ((,class (:background "gray95"))))
   `(p4-diff-ins-face ((,class (:foreground "blue"))))
   `(paren-blink-off ((,class (:foreground "gray80"))))
   `(paren-face-match ((,class (:background "turquoise"))))
   `(paren-face-mismatch ((,class (:background "purple" :foreground "white"))))
   `(paren-face-no-match ((,class (:background "yellow" :foreground "black"))))
   `(paren-match ((,class (:background "darkseagreen2"))))
   `(paren-mismatch ((,class (:background "DeepPink" :foreground "black"))))
   `(paren-mismatch-face ((,class (:bold t :weight bold))))
   `(paren-no-match-face ((,class (:bold t :weight bold))))
   `(pointer ((,class (nil))))
   `(primary-selection ((,class (:background "dark violet"))))
   `(pulse-highlight-face ((,class (:background "#FFFFAA"))))
   `(pulse-highlight-start-face ((,class (:background "#FFFFAA"))))
   `(qt-classes-face ((,class (:foreground "Red"))))
   `(query-replace ((,class (:background "yellow"))))
   `(red ((,class (nil))))
   `(region ((,class (:background "OliveDrab3"))))
   `(right-margin ((,class (nil))))
   `(rst-level-1-face ((,class (:background "darkgreen85"))))
   `(rst-level-2-face ((,class (:background "darkgreen78"))))
   `(rst-level-3-face ((,class (:background "darkgreen71"))))
   `(rst-level-4-face ((,class (:background "darkgreen64"))))
   `(rst-level-5-face ((,class (:background "darkgreen57"))))
   `(rst-level-6-face ((,class (:background "darkgreen50"))))
   `(scroll-bar ((,class (nil))))
   `(secondary-selection ((,class (:background "green4"))))
   `(semantic-decoration-on-fileless-includes ((,class (:background "#f0fdf0"))))
   `(semantic-decoration-on-includes ((,class (nil))))
   `(semantic-decoration-on-private-members-face ((,class (:background "#8fffff"))))
   `(semantic-decoration-on-protected-members-face ((,class (:background "#fffff8"))))
   `(semantic-decoration-on-unknown-includes ((,class (:background "#fff0f0"))))
   `(semantic-decoration-on-unparsed-includes ((,class (:background "#ffff55"))))
   `(semantic-dirty-token-face ((,class (:background "lightyellow"))))
   `(semantic-highlight-edits-face ((,class (:background "gray90"))))
   `(semantic-highlight-func-current-tag-face ((,class (:background "gray90"))))
   `(semantic-tag-boundary-face ((,class (:overline "blue"))))
   `(semantic-unmatched-syntax-face ((,class (:underline "red"))))
   `(senator-intangible-face ((,class (:foreground "gray75"))))
   `(senator-momentary-highlight-face ((,class (:background "gray30"))))
   `(senator-read-only-face ((,class (:background "#664444"))))
   `(sgml-comment-face ((,class (:foreground "dark turquoise"))))
   `(sgml-doctype-face ((,class (nil))))
   `(sgml-end-tag-face ((,class (nil))))
   `(sgml-entity-face ((,class (nil))))
   `(sgml-ignored-face ((,class (nil))))
   `(sgml-ms-end-face ((,class (:foreground "green"))))
   `(sgml-ms-start-face ((,class (:foreground "green"))))
   `(sgml-pi-face ((,class (:foreground "lime green"))))
   `(sgml-sgml-face ((,class (nil))))
   `(sgml-short-ref-face ((,class (:foreground "deep sky blue"))))
   `(sgml-start-tag-face ((,class (nil))))
   `(shadow ((,class (nil))))
   `(shell-option-face ((,class (:foreground "blue"))))
   `(shell-output-2-face ((,class (:foreground "darkseagreen"))))
   `(shell-output-3-face ((,class (:foreground "slategrey"))))
   `(shell-output-face ((,class (:foreground "palegreen"))))
   `(shell-prompt-face ((,class (:foreground "red"))))
   `(show-paren-match ((,class (:background "DodgerBlue2"))))
   `(show-paren-mismatch ((,class (:bold t :background "purple" :foreground "white" :weight bold))))
   `(show-tabs-space-face ((,class (:foreground "yellow"))))
   `(show-tabs-tab-face ((,class (:foreground "red"))))
   `(speedbar-button-face ((,class (:bold t :foreground "medium blue" :weight bold))))
   `(speedbar-directory-face ((,class (:bold t :foreground "blue" :weight bold))))
   `(speedbar-file-face ((,class (:bold t :foreground "brown" :weight bold))))
   `(speedbar-highlight-face ((,class (:background "coral" :foreground "black"))))
   `(speedbar-selected-face ((,class (:foreground "red" :underline t))))
   `(speedbar-separator-face ((,class (:background "blue" :foreground "white" :overline "gray"))))
   `(speedbar-tag-face ((,class (:foreground "DarkGreen"))))
   `(swbuff-current-buffer-face ((,class (:bold t :foreground "red" :weight bold))))
   `(template-message-face ((,class (:bold t :weight bold))))
   `(term-black ((,class (:foreground "black"))))
   `(term-blackbg ((,class (:background "black"))))
   `(term-blue ((,class (:foreground "blue"))))
   `(term-bluebg ((,class (:background "blue"))))
   `(term-bold ((,class (:bold t :weight bold))))
   `(term-cyan ((,class (:foreground "cyan"))))
   `(term-cyanbg ((,class (:background "cyan"))))
   `(term-default ((,class (:stipple nil :background "DarkSlateGray" :foreground "palegreen" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "lucida sans typewriter"))))
   `(term-default-bg ((,class (nil))))
   `(term-default-bg-inv ((,class (nil))))
   `(term-default-fg ((,class (nil))))
   `(term-default-fg-inv ((,class (nil))))
   `(term-green ((,class (:foreground "green"))))
   `(term-greenbg ((,class (:background "green"))))
   `(term-invisible ((,class (nil))))
   `(term-invisible-inv ((,class (nil))))
   `(term-magenta ((,class (:foreground "magenta"))))
   `(term-magentabg ((,class (:background "magenta"))))
   `(term-red ((,class (:foreground "red"))))
   `(term-redbg ((,class (:background "red"))))
   `(term-underline ((,class (:underline t))))
   `(term-white ((,class (:foreground "white"))))
   `(term-whitebg ((,class (:background "white"))))
   `(term-yellow ((,class (:foreground "yellow"))))
   `(term-yellowbg ((,class (:background "yellow"))))
   `(text-cursor ((,class (:background "grey15" :foreground "gainsboro"))))
   `(tool-bar ((,class (nil))))
   `(tooltip ((,class (:background "lightyellow" :foreground "black"))))
   `(trailing-whitespace ((,class (:background "red"))))
   `(underline ((,class (:underline t))))
   `(variable-pitch ((,class (:family "helv"))))
   `(vc-annotate-face-0046FF ((,class (nil))))
   `(vcursor ((,class (:background "cyan" :foreground "blue" :underline t))))
   `(vertical-border ((,class (nil))))
   `(vertical-divider ((,class (nil))))
   `(vhdl-font-lock-attribute-face ((,class (:foreground "Orchid"))))
   `(vhdl-font-lock-directive-face ((,class (:foreground "CadetBlue"))))
   `(vhdl-font-lock-enumvalue-face ((,class (:foreground "Gold4"))))
   `(vhdl-font-lock-function-face ((,class (:foreground "Orchid4"))))
   `(vhdl-font-lock-prompt-face ((,class (:bold t :foreground "Red" :weight bold))))
   `(vhdl-font-lock-reserved-words-face ((,class (:bold t :foreground "Orange" :weight bold))))
   `(vhdl-font-lock-translate-off-face ((,class (:background "LightGray"))))
   `(vhdl-speedbar-architecture-face ((,class (:foreground "Blue"))))
   `(vhdl-speedbar-architecture-selected-face ((,class (:foreground "Blue" :underline t))))
   `(vhdl-speedbar-configuration-face ((,class (:foreground "DarkGoldenrod"))))
   `(vhdl-speedbar-configuration-selected-face ((,class (:foreground "DarkGoldenrod" :underline t))))
   `(vhdl-speedbar-entity-face ((,class (:foreground "ForestGreen"))))
   `(vhdl-speedbar-entity-selected-face ((,class (:foreground "ForestGreen" :underline t))))
   `(vhdl-speedbar-instantiation-face ((,class (:foreground "Brown"))))
   `(vhdl-speedbar-instantiation-selected-face ((,class (:foreground "Brown" :underline t))))
   `(vhdl-speedbar-package-face ((,class (:foreground "Grey50"))))
   `(vhdl-speedbar-package-selected-face ((,class (:foreground "Grey50" :underline t))))
   `(viper-minibuffer-emacs-face ((,class (:background "darkseagreen2" :foreground "Black"))))
   `(viper-minibuffer-insert-face ((,class (:background "pink" :foreground "Black"))))
   `(viper-minibuffer-vi-face ((,class (:background "grey" :foreground "DarkGreen"))))
   `(viper-replace-overlay-face ((,class (:background "darkseagreen2" :foreground "Black"))))
   `(viper-search-face ((,class (:background "khaki" :foreground "Black"))))
   `(vvb-face ((,class (:background "pink" :foreground "black"))))
   `(w3m-anchor ((,class (:foreground "blue"))))
   `(w3m-arrived-anchor ((,class (:foreground "navy"))))
   `(w3m-bold ((,class (:bold t :weight bold))))
   `(w3m-current-anchor ((,class (:bold t :underline t :weight bold))))
   `(w3m-form ((,class (:foreground "brown" :underline t))))
   `(w3m-form-button ((,class (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
   `(w3m-form-button-mouse ((,class (:background "DarkSeaGreen1" :foreground "black" :box (:line-width 2 :style released-button)))))
   `(w3m-form-button-pressed ((,class (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
   `(w3m-header-line-location-content ((,class (:background "Gray90" :foreground "DarkGoldenrod"))))
   `(w3m-header-line-location-title ((,class (:background "Gray90" :foreground "Blue"))))
   `(w3m-history-current-url ((,class (:background "SkyBlue4" :foreground "LightSkyBlue"))))
   `(w3m-image ((,class (:foreground "ForestGreen"))))
   `(w3m-image-anchor ((,class (:background "light yellow"))))
   `(w3m-insert ((,class (:foreground "purple"))))
   `(w3m-italic ((,class (:italic t :slant italic))))
   `(w3m-session-select ((,class (:foreground "dark blue"))))
   `(w3m-session-selected ((,class (:bold t :foreground "dark blue" :underline t :weight bold))))
   `(w3m-strike-through ((,class (:strike-through t))))
   `(w3m-tab-background ((,class (:background "LightSteelBlue" :foreground "black"))))
   `(w3m-tab-mouse ((,class (:background "Gray75" :foreground "white" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-selected ((,class (:background "Gray90" :foreground "black" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-selected-background ((,class (:background "LightSteelBlue" :foreground "black"))))
   `(w3m-tab-selected-retrieving ((,class (:background "Gray90" :foreground "red" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-unselected ((,class (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-unselected-retrieving ((,class (:background "Gray70" :foreground "OrangeRed" :box (:line-width -1 :style released-button)))))
   `(w3m-tab-unselected-unseen ((,class (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
   `(w3m-underline ((,class (:underline t))))
   `(which-func ((,class (:italic t :bold t :weight bold :slant italic :foreground "SlateBlue"))))
   `(widget ((,class (:background "gray75"))))
   `(widget-button ((,class (:bold t :weight bold))))
   `(widget-button-pressed ((,class (:foreground "red"))))
   `(widget-documentation ((,class (:foreground "dark green"))))
   `(widget-field ((,class (:background "navy" :foreground "white"))))
   `(widget-inactive ((,class (:foreground "dim gray"))))
   `(widget-single-line-field ((,class (:background "royalblue" :foreground "white"))))
   `(woman-bold-face ((,class (:bold t :weight bold))))
   `(woman-italic-face ((,class (nil))))
   `(woman-unknown-face ((,class (nil))))
   `(x-face ((,class (:background "white"))))
   `(xref-keyword-face ((,class (:foreground "blue"))))
   `(xref-list-pilot-face ((,class (:foreground "navy"))))
   `(xref-list-symbol-face ((,class (:foreground "navy"))))
   `(yellow ((,class (nil))))
   `(web-mode-css-prop-face ((,class (:foreground "DarkViolet"))))
   `(web-mode-css-psudo-class-face ((,class (:foreground "DarkGreen"))))
   `(web-mode-css-rule-face ((,class (:foreground "orange4"))))
   `(web-mode-html-attr-name-face ((,class (:foreground "green4"))))
   `(web-mode-html-attr-cyan-face ((,class (:foreground "DarkSlateGray"))))
   `(web-mode-html-attr-value-face ((,class (:foreground "DarkRed"))))
   `(web-mode-html-tag-face ((,class (:foreground "blue"))))
   `(zmacs-region ((,class (:background "royalblue"))))))

(provide-theme 'xemacs)



